import Lax3Proofs.BotEval
import Lax3Proofs.CoverDegree
import Lax3Proofs.FormulaTables
import Lax3Proofs.RamAugment
import Lax3Proofs.RamBfsPaths
import Lax3Proofs.RamCover
import Lax3Proofs.RamScatter
import Lax3Proofs.SplitterWinOracle

/-!
The **driver**: the word-RAM program that decides a first-order sentence
on a graph of a nowhere dense class, assembled from the passes of this
submission, together with its correctness skeleton.

This file delivers the graph-side decision program and the statement of
its correctness, with the per-level obligations isolated. It is stage
one of two: the program text, the name management, the specifications of
the phases, the top-level theorem *proved from those specifications*,
and the semantic glue that no program obligation should have to carry.
The campaign headline — `Lax3.ModelChecking` — is not this file's
business and is not stated here.

# The shape of the recursion

`Lax3Proofs.Evaluator` fixes the mathematics: at each level a cover is
taken, the vertex is assigned to a cluster, a batch is isolated, the
formula is relativized to the cluster and translated through the
isolation, and the recursion descends one level with one round of the
splitter game fewer. `Lax3Proofs.FormulaTables` fixes what is tabulated:
the finite list `tablesAt … j` of one-variable formulas of depth `j`,
laid out before the run, together with the boolean combination
`bcOf (stepFml j β)` that each of them is decomposed into. The driver
runs that recursion **downwards from the root**: `driverAt j` computes,
over the arena its masks cut out, the full table row of every formula of
`tablesAt … j`, and it computes it by calling `driverAt (j + 1)` once per
cluster and reading the boolean combinations back.

The recursion bottoms out at `j = ℓ`, where `ℓ` is the round bound of the
splitter game on the class. That is not a fuel cut-off: by
`Lax3Proofs.SplitterWinOracle.reachedO_length_lt` no play of the oracle's
strategy lasts `ℓ` rounds, so the arena at depth `ℓ` is *edgeless*, and
the base case is the unary-structure evaluation of `Lax3Proofs.BotEval` —
row lookups, equality tests, and a witness search over the environment
and one representative per realized colour row. `PlayOk` below is the
invariant that delivers it, and `eq_bot_of_playOk_full` is the delivery.

# Two arenas per level

The driver carries **two** masks per depth. The *work* arena `alv j` is
the one the tables are about: it is the arena of `Evaluator.stepArena`,
the cluster restriction followed by the batch isolation. The *game*
arena `gam j` is the one the splitter strategy is played in: the ball
restriction followed by the same batch isolation, which is exactly
`SplitterWinOracle.nextArenaO`. Keeping both is what makes the game
invariant an equality rather than an approximation — the recorded rounds
are literally a `ReachedO` play — while the work arena, which the cover
has cut down further, is a subgraph of the game arena and inherits the
edgelessness at the bottom. The one lemma that connects them is
`stepArena_le_nextArenaO`, and `playOk_succ` is the descent step it
proves.

# Names

Every per-depth object is an array or a scalar whose name carries the
depth, generated by string interpolation at construction time: the two
masks `alv j`/`gam j`, the cluster indicator `clu j`, the ball indicator
`bal j`, the batch indicator `bat j`, the restricted arena `res j`, the
connector `ctr j`, the colour arrays `col j c` for `c < sigL cap mb j`,
the table arrays `tab j i` for `i` a position of `tablesAt … j`, and the
scatter flags `flg j i k`. The sub-programs this file calls — the
search, the path extraction, the cover, the elimination, the
augmentation, the scatter pass — all address *fixed* array names, so a
call is preceded by a copy of the depth's array into the name the callee
reads. `copyCom` is that copy and it is the whole of the calling
convention.

The number of colour arrays at depth `j` is `sigL cap mb j`, which grows
by a factor of about `cap + 2` per level: the program text is a constant
of the sentence and the three parameters, and an enormous one. That is
the algorithm of Grohe–Kreutzer–Siebertz, not an artefact of the
formalization — the tower is in the tables too — and it is invisible to
the running time, which is what the input-size analysis measures.

# Re-initialization per cluster

Every array of depth `j + 1` — the masks, the colour arrays, the tables
— is written from scratch at the start of each cluster of depth `j`, and
the deeper levels do the same recursively. That is *correct*: nothing of
a cluster survives into the next one, so no clause of any invariant has
to be re-established across the boundary, and each cluster's postcondition
is about the vertices assigned to it alone. It is also wasteful, and
deliberately so at this stage: the cost of the driver is a separate
wave's business, and the touched-only revision — re-initializing only
the cells the previous cluster wrote — changes the program's cost and
not its meaning. Nothing in this file's specifications mentions a cost
beyond carrying one as a parameter.

# What is proved here, and what is isolated

Proved:

* the padding of a batch to the fixed width `mb` (`exists_pad_enum`),
  and the reason `mb` is `ℓ · (2·cap + 1)` and not another number
  (`exists_pad_batch`);
* the game invariant and its moves — `playOk_zero`, `playOk_succ`,
  `playOk_bot`, `playOk_stepArenaP`, and `eq_bot_of_playOk_full`, which
  is the base case's whole justification;
* the two bridges between the program's arrays and the mathematics:
  `masked_step`, that the mask the driver writes cuts out
  `Evaluator.stepArena`, and `stepArenaP_eq`, that the batch read as an
  enumeration and the batch read as a set give the same arena;
* **the descent step** `sat_iff_eval_step` — that satisfaction of a
  tabled formula at a vertex of the arena is the value of the formula's
  own boolean combination over the depth-`(j+1)` tables and the scatter
  values of the cluster arena — which is
  `Evaluator.tablesLocal_iff_sat`'s chain read between two `Sat`s rather
  than between a table and a `Sat`, so that the splitter win is needed
  nowhere in it;
* **the sentence step** `sat_iff_eval_sentence`, the same statement at
  the root, and `sat_exU_bot_of_repr_all`, the base case's witness search
  with the off-tuple test dropped.

Isolated, each as a named `Prop` threaded as a hypothesis, each with a
docstring splitting it into its sub-walks in the manner of
`Lax3Proofs.RamElim.Implements`: `DecodeImplements`, `OrderImplements`,
`CoverImplements`, `ClusterStepImplements`,
`BaseImplements`, `SentenceImplements`, and the composition
`LevelImplements`, which carries the first six as hypotheses of its own
exactly as `Lax3Proofs.RamAugment.Implements` carries `ElimAvail`. No
`sorry` and no axiom: an obligation is a hypothesis, and `driver_correct`
is a theorem about programs that satisfy them.

# Formalization notes

No concept-side definition is handed to a tactic. `Sat`, `DRank`,
`IsLocal`, `WithinDist`, `ball`, `deleteVerts`, `BC.eval`, `BC.atoms`,
`SplitterWins` and the scatter definitions are taken apart through the
clause lemmas of `Lax3Proofs.SyntaxLemmas`, `Lax3Proofs.BCAlgebra`,
`Lax3Proofs.SplitterBasics` and `Lax3Proofs.Evaluator`; `greedyChoice`'s
one projection is named once, below. The definitions introduced here are
unfolded freely.

The tables are `Classical.choose` of the locality theorem, so
`tablesAt` is noncomputable and so is every program text that indexes by
it. That costs a worked example — the program cannot be run by
`#guard` — and nothing else: `Com` is data either way, and every
specification below is about a `Run` of it.
-/

namespace Lax3Proofs.RamDriver

open Lax3.ColoredGraphs Lax3.DistFO Lax3.Locality Lax3.ScatterSentences
open Lax3.SplitterGame
open Lax12.UniformQuasiWideness
open Lax3Proofs.Horizon Lax3Proofs.SyntaxLemmas Lax3Proofs.WalkDistance
open Lax3Proofs.FormulaTables Lax3Proofs.SplitterWin Lax3Proofs.SplitterWinOracle
open Lax3Proofs.RamBfs (masked masked_adj CsrGraph)
open Lax13Proofs.Imp Lax13Proofs.Reasoning Lax13Proofs.Reasoning.Lib

/-! ### Three additions to the reasoning kit

A `Run` cannot change the length of an array, and — being a run of the
bounded semantics — cannot put a value at or above the bound into one.
Both are about arrays the command *does* write, so neither is a frame
condition; both are the induction of `BigStep.arrs_eq` with a different
conclusion, and both are what lets a memory clause cross a phase that
writes the array it speaks about. The third is the translation between
the two ways of saying an array is there: having length `n`, and being
`arrOf n g` for some `g`. -/

/-- A big step leaves the length of every array where it was. -/
theorem bigStep_length_arrs {c : Com} {σ σ' : Env} {k : ℕ} (h : BigStep c σ σ' k)
    (a : String) : (σ'.arrs a).length = (σ.arrs a).length := by
  induction h with
  | skip => rfl
  | assign _ => rfl
  | store _ _ _ => exact length_arrs_setArr ..
  | seq _ _ ih ih' => rw [ih', ih]
  | ite_true _ _ ih => exact ih
  | ite_false _ _ ih => exact ih
  | while_true _ _ _ ih ih' => rw [ih', ih]
  | while_false _ => rfl
  | read _ => rfl
  | write _ => rfl

/-- The same, on a `Run`. -/
theorem run_length_arrs {B : ℕ} {c : Com} {σ σ' : Env} {K : ℕ} (h : Run B c σ σ' K)
    (a : String) : (σ'.arrs a).length = (σ.arrs a).length := by
  obtain ⟨_, _, hbs⟩ := h.bigStep
  exact bigStep_length_arrs hbs a

/-- A bounded run puts only words into an array, so an array all of
whose cells are words still has only words in it. -/
theorem bigStepB_mem_arrs_lt {B : ℕ} {c : Com} {σ σ' : Env} {k : ℕ} (h : BigStepB B c σ σ' k)
    (a : String) (hσ : ∀ v ∈ σ.arrs a, v < B) : ∀ v ∈ σ'.arrs a, v < B := by
  induction h with
  | skip => exact hσ
  | assign _ => exact hσ
  | store _ he _ =>
      intro u hu
      rw [arrs_setArr] at hu
      split at hu
      · rcases List.mem_or_eq_of_mem_set hu with hu' | rfl
        · exact hσ u (by subst_vars; exact hu')
        · exact Expr.lt_of_evalB he
      · exact hσ u hu
  | seq _ _ ih ih' => exact ih' (ih hσ)
  | ite_true _ _ ih => exact ih hσ
  | ite_false _ _ ih => exact ih hσ
  | while_true _ _ _ ih ih' => exact ih' (ih hσ)
  | while_false _ => exact hσ
  | read _ => exact hσ
  | write _ => exact hσ

/-- The same, on a `Run`. -/
theorem run_mem_arrs_lt {B : ℕ} {c : Com} {σ σ' : Env} {K : ℕ} (h : Run B c σ σ' K)
    (a : String) (hσ : ∀ v ∈ σ.arrs a, v < B) : ∀ v ∈ σ'.arrs a, v < B := by
  obtain ⟨_, _, hbs⟩ := h
  exact bigStepB_mem_arrs_lt hbs a hσ

/-- An array of length `n` is `arrOf` of something. -/
theorem exists_arrOf {l : List ℕ} {n : ℕ} (h : l.length = n) :
    ∃ g, l = arrOf n g := by
  refine ⟨fun i => l.getD i 0, List.ext_getElem (by simp [h]) fun k h₁ h₂ => ?_⟩
  simp only [arrOf, List.getElem_map, List.getElem_range]
  rw [List.getD_eq_getElem?_getD, List.getElem?_eq_getElem h₁]
  rfl

/-- An array of length `n` all of whose cells are words is
`RamScatter.Words`. -/
theorem words_of_length {B n : ℕ} {a : String} {σ : Env} (hlen : (σ.arrs a).length = n)
    (hlt : ∀ v ∈ σ.arrs a, v < B) : RamScatter.Words B n a σ := by
  obtain ⟨g, hg⟩ := exists_arrOf hlen
  refine ⟨g, hg, fun i hi => hlt (g i) ?_⟩
  rw [hg]
  exact List.mem_map.2 ⟨i, List.mem_range.2 hi, rfl⟩

/-! ### One projection of the scatter choice

The evaluator's scatter atoms are evaluated at `greedyChoice`, and the
pass of `Lax3Proofs.RamScatter` decides the cardinality of `greedySet`.
The two are the same number by definition; naming it once keeps the
concept-side projection out of every tactic below. -/

/-- The greedy choice's value is the size of the greedy set. -/
theorem greedyChoice_size {n : ℕ} (G : SimpleGraph (Fin n)) (r : ℕ) (X : Set (Fin n)) :
    greedyChoice.size G r X = (greedySet G r X).ncard := rfl

/-! ### Positions in a list

A table is addressed by position, and the atoms of a boolean
combination arrive as members of a list. `posOf` turns the second into
the first; it is the only thing the readback needs of a list, and it is
classical because `DistFO` carries no decidable equality. -/

open Classical in
/-- The position of the first occurrence of `x` in `l`, and `l.length`
if there is none. -/
noncomputable def posOf {X : Type*} (x : X) : List X → ℕ
  | [] => 0
  | y :: ys => if y = x then 0 else posOf x ys + 1

/-- **A member of a list sits at its own position.** -/
theorem getElem_posOf {X : Type*} {x : X} :
    ∀ {l : List X}, x ∈ l → ∃ h : posOf x l < l.length, l[posOf x l] = x := by
  classical
  intro l
  induction l with
  | nil => intro h; exact absurd h (by simp)
  | cons y ys ih =>
    intro h
    by_cases hy : y = x
    · refine ⟨by simp [posOf, hy], ?_⟩
      simp only [posOf, if_pos hy]
      simpa using hy
    · have hmem : x ∈ ys := by
        rcases List.mem_cons.mp h with rfl | h'
        · exact absurd rfl hy
        · exact h'
      obtain ⟨hlt, heq⟩ := ih hmem
      refine ⟨by simp [posOf, hy]; omega, ?_⟩
      simp only [posOf, if_neg hy]
      simpa using heq

/-! ### Padding a batch to the fixed width

`Lax3Proofs.Isolate` reads a batch enumeration only through its range,
and `FormulaTables.range_comp_of_surjective` is the observation that
repeating entries leaves the range alone. What is left is to produce the
repetition, which is where the batch bound and the fact that a batch
contains its own connector are spent. -/

/-- **A nonempty vertex set of at most `mb` elements is the range of a
map from `Fin mb`.** The evaluator's own enumeration, precomposed with
the surjection that sends everything past the end back to the first
entry. -/
theorem exists_pad_enum {n mb : ℕ} {W : Set (Fin n)} (hcard : W.ncard ≤ mb)
    (hne : W.Nonempty) : ∃ w : Fin mb → Fin n, Set.range w = W := by
  have hpos : 0 < W.ncard := by
    rcases Nat.eq_zero_or_pos W.ncard with h | h
    · exact absurd ((Set.ncard_eq_zero (Set.toFinite W)).mp h) (Set.nonempty_iff_ne_empty.mp hne)
    · exact h
  refine ⟨Evaluator.enumOf W ∘
    (fun i : Fin mb => (⟨min (i : ℕ) (W.ncard - 1), by omega⟩ : Fin W.ncard)), ?_⟩
  rw [FormulaTables.range_comp_of_surjective (Evaluator.enumOf W) ?_]
  · exact Evaluator.range_enumOf W
  · intro c
    have hc := c.isLt
    refine ⟨⟨(c : ℕ), lt_of_lt_of_le c.isLt hcard⟩, Fin.ext ?_⟩
    show min (c : ℕ) (W.ncard - 1) = (c : ℕ)
    omega

/-! ### The two objects of one cluster step, at the padded width

`Evaluator.stepArena` and `Evaluator.stepColoring` are stated at the
batch's own cardinality; the driver always enumerates by exactly `mb`
entries, so the same two objects are restated at an arbitrary
enumeration. Nothing changes: the arena is the range's isolation either
way, and the colouring is `Evaluator.isoColoring` at that
enumeration. -/

variable {n : ℕ}

/-- The arena of one cluster step: restrict to the cluster, then isolate
the range of the padded batch enumeration. -/
noncomputable def stepArenaP (A : SimpleGraph (Fin n)) (X : Set (Fin n)) {mb : ℕ}
    (w : Fin mb → Fin n) : SimpleGraph (Fin n) :=
  deleteVerts (deleteVerts A Xᶜ) (Set.range w)

/-- The colouring of one cluster step: relativize to the cluster, then
record the profiles of the padded batch and of the colours. -/
noncomputable def stepColoringP (cap : ℕ) {L mb : ℕ} (A : SimpleGraph (Fin n))
    (col : Coloring n L) (X : Set (Fin n)) (w : Fin mb → Fin n) :
    Coloring n (Evaluator.isoPalette (L + 1) mb cap) :=
  Evaluator.isoColoring (cap := cap) (deleteVerts A Xᶜ) (Evaluator.relColoring col X) w

/-- The padded arena is the arena of whatever set the enumeration
enumerates: the join point of this file's two halves, since the game
invariant speaks of the batch as a set and the descent speaks of it as
an enumeration. -/
theorem stepArenaP_eq (A : SimpleGraph (Fin n)) (X : Set (Fin n)) {mb : ℕ}
    (w : Fin mb → Fin n) {W : Set (Fin n)} (hw : Set.range w = W) :
    stepArenaP A X w = deleteVerts (deleteVerts A Xᶜ) W := by
  rw [stepArenaP, hw]

/-- **The mask arithmetic of a cluster step.** The arena of the mask the
driver writes — alive, in the cluster, out of the batch, which is what
`andCom` followed by `subCom` computes — is the cluster step's arena.
This is the bridge between the program's three arrays and
`Evaluator.stepArena`; the game arena's is the same statement with the
ball's indicator in place of the cluster's. -/
theorem masked_step {G : SimpleGraph (Fin n)} (M Xa Wa : ℕ → ℕ) {X W : Set (Fin n)}
    (hX : ∀ v : Fin n, v ∈ X ↔ Xa (v : ℕ) ≠ 0)
    (hW : ∀ v : Fin n, v ∈ W ↔ Wa (v : ℕ) ≠ 0) :
    masked G (fun a => M a * Xa a * (1 - Wa a)) =
      deleteVerts (deleteVerts (masked G M) Xᶜ) W := by
  have hcell : ∀ a : Fin n, (M (a : ℕ) * Xa (a : ℕ) * (1 - Wa (a : ℕ)) ≠ 0) ↔
      (M (a : ℕ) ≠ 0 ∧ a ∈ X ∧ a ∉ W) := by
    intro a
    rw [hX a, hW a]
    constructor
    · intro h
      refine ⟨fun hc => h (by rw [hc]; ring), fun hc => h (by rw [hc]; ring), fun hc => h ?_⟩
      obtain ⟨t, ht⟩ : ∃ t, Wa (a : ℕ) = t + 1 := ⟨Wa (a : ℕ) - 1, by omega⟩
      rw [ht, show 1 - (t + 1) = 0 by omega, Nat.mul_zero]
    · rintro ⟨h1, h2, h3⟩
      have h4 : Wa (a : ℕ) = 0 := by by_contra hc; exact h3 hc
      rw [h4]
      simpa using Nat.mul_ne_zero h1 h2
  ext u v
  rw [masked_adj, SplitterBasics.deleteVerts_adj, SplitterBasics.deleteVerts_adj, masked_adj]
  rw [hcell u, hcell v]
  simp only [Set.mem_compl_iff, not_not]
  tauto

/-- **A cluster step is a subgraph of a splitter round.** The cluster
lies in the ball the round restricts to and the step isolates at least
what the round isolates, so every edge that survives the step survives
the round. This is the one inequality that lets the driver keep the game
invariant as an equality while its own arena is cut down further by the
cover. -/
theorem stepArena_le_nextArenaO {cap : ℕ} {O : PathOracle n (2 * cap)}
    {A P : SimpleGraph (Fin n)} {rounds : List (Round n)} {v : Fin n} {X W : Set (Fin n)}
    (hAP : A ≤ P) (hX : X ⊆ ball A (2 * cap) v) (hW : batchO O rounds P v ⊆ W) :
    deleteVerts (deleteVerts A Xᶜ) W ≤ nextArenaO O P v rounds := by
  intro a b hab
  obtain ⟨hab', haW, hbW⟩ := SplitterBasics.deleteVerts_adj.mp hab
  obtain ⟨hadj, haX, hbX⟩ := SplitterBasics.deleteVerts_adj.mp hab'
  refine SplitterBasics.deleteVerts_adj.mpr
    ⟨SplitterBasics.deleteVerts_adj.mpr ⟨hAP hadj, ?_, ?_⟩, fun hc => haW (hW hc),
      fun hc => hbW (hW hc)⟩
  · exact fun hc => hc (ball_mono_graph v hAP (hX (not_not.mp haX)))
  · exact fun hc => hc (ball_mono_graph v hAP (hX (not_not.mp hbX)))

/-! ### The game invariant

What the driver knows about the splitter game at a node of its recursion
tree, of depth `j`: either the work arena is already edgeless — some
connector on the way down turned out to be isolated, which ends the play
at once — or the connectors and game arenas it recorded are a play of
the oracle's strategy, of which the work arena is a subgraph.

The invariant is stated per *node*: the recursion is a tree, one branch
per cluster, and each branch has its own history. Full re-initialization
per cluster is what makes that legitimate — no branch sees another's
arrays. -/

/-- The driver's game state at a node of depth `j`. -/
def PlayOk (cap : ℕ) (O : PathOracle n (2 * cap)) (G : SimpleGraph (Fin n)) (j : ℕ)
    (A : SimpleGraph (Fin n)) : Prop :=
  A = ⊥ ∨ ∃ (rounds : List (Round n)) (P : SimpleGraph (Fin n)),
    ReachedO O G rounds P ∧ rounds.length = j ∧ A ≤ P

variable {cap : ℕ} {O : PathOracle n (2 * cap)} {G : SimpleGraph (Fin n)}

/-- At the root nothing has been played and the work arena is the input
graph. -/
theorem playOk_zero (O : PathOracle n (2 * cap)) (G : SimpleGraph (Fin n)) :
    PlayOk cap O G 0 G :=
  Or.inr ⟨[], G, ReachedO.nil, rfl, le_rfl⟩

/-- An edgeless arena stays edgeless: every cluster step of it isolates
inside a graph with no edges. -/
theorem playOk_bot {A : SimpleGraph (Fin n)} (hA : A = ⊥) (X W : Set (Fin n)) (j : ℕ) :
    PlayOk cap O G (j + 1) (deleteVerts (deleteVerts A Xᶜ) W) := by
  refine Or.inl (le_bot_iff.mp fun a b hab => ?_)
  obtain ⟨hab', -, -⟩ := SplitterBasics.deleteVerts_adj.mp hab
  obtain ⟨hadj, -, -⟩ := SplitterBasics.deleteVerts_adj.mp hab'
  rw [hA] at hadj
  exact absurd hadj (by simp)

/-- **The descent step of the game invariant.** At a node whose recorded
rounds reach the game arena `P`, playing the connector `v` and a batch
containing the strategy's own lands one level down: either the connector
still had an edge, in which case the rounds extended by `(v, P)` reach
`nextArenaO`, of which the cluster step is a subgraph, or it did not, in
which case the round leaves an edgeless arena and so does the cluster
step. -/
theorem playOk_succ {rounds : List (Round n)} {P A : SimpleGraph (Fin n)} {j : ℕ}
    (hR : ReachedO O G rounds P) (hlen : rounds.length = j) (hAP : A ≤ P) {v : Fin n}
    {X W : Set (Fin n)} (hX : X ⊆ ball A (2 * cap) v) (hW : batchO O rounds P v ⊆ W) :
    PlayOk cap O G (j + 1) (deleteVerts (deleteVerts A Xᶜ) W) := by
  have hle := stepArena_le_nextArenaO hAP hX hW
  by_cases hv : ∃ u, P.Adj v u
  · exact Or.inr ⟨(v, P) :: rounds, nextArenaO O P v rounds, ReachedO.step hR hv,
      by simp only [List.length_cons, hlen], hle⟩
  · refine Or.inl (le_bot_iff.mp ?_)
    rw [← nextArenaO_eq_bot_of_isolated O (fun z hz => hv ⟨z, hz⟩) rounds]
    exact hle

/-- **The game invariant descends along the padded batch.** The form the
cluster step consumes: the two halves of this file meet here, since the
arena the descent rewrites into (`stepArenaP`, an enumeration) is the
arena the game invariant descends to (a set). -/
theorem playOk_stepArenaP {rounds : List (Round n)} {P A : SimpleGraph (Fin n)} {j mb : ℕ}
    (hR : ReachedO O G rounds P) (hlen : rounds.length = j) (hAP : A ≤ P) {v : Fin n}
    {X : Set (Fin n)} (hX : X ⊆ ball A (2 * cap) v) (w : Fin mb → Fin n)
    (hw : Set.range w = batchO O rounds P v) :
    PlayOk cap O G (j + 1) (stepArenaP A X w) := by
  rw [stepArenaP_eq A X w hw]
  exact playOk_succ hR hlen hAP hX (le_refl _)

/-- **The batch fits the fixed width, and is enumerated by it.** One
vertex plus one path of at most `2·cap + 1` vertices per earlier round is
at most `ℓ · (2·cap + 1)` vertices, and the batch is never empty since it
contains its own connector. So `mb := ℓ · (2·cap + 1)` is the width at
which the driver's padded enumeration exists — which is the choice of
`mb` the whole development runs on, and the reason it is that number and
not another. -/
theorem exists_pad_batch {ℓ : ℕ} {rounds : List (Round n)} {P : SimpleGraph (Fin n)}
    (hlen : rounds.length < ℓ) (v : Fin n) :
    ∃ w : Fin (ℓ * (2 * cap + 1)) → Fin n, Set.range w = batchO O rounds P v :=
  exists_pad_enum (batchO_ncard_le_of_lt O rounds P v hlen)
    ⟨v, mem_batchO (self_mem_genSetO O rounds v) (mem_ball_self P (2 * cap) v)⟩

/-- **Budget exhaustion is the base case.** At depth `ℓ`, the round
bound the class's quasi-wideness produces, the work arena is edgeless:
a play of that length cannot be reached, so the only surviving branch of
`PlayOk` is the one that says so. This is what
`Lax3Proofs.BotEval` is applied to, and it is why the driver's recursion
needs no test for an edgeless arena. -/
theorem eq_bot_of_playOk_full {N : ℕ → ℕ} {s : ℕ}
    (hQ : ∀ Pt : Set (Fin n), N (2 * s + 2) ≤ Pt.ncard →
      ∃ S Bd : Set (Fin n), S.ncard ≤ s ∧ Bd ⊆ Pt \ S ∧ 2 * s + 2 ≤ Bd.ncard ∧
        DistIndependent (deleteVerts G S) (2 * cap) Bd)
    {A : SimpleGraph (Fin n)} (h : PlayOk cap O G (N (2 * s + 2)) A) : A = ⊥ := by
  rcases h with h | ⟨rounds, P, hR, hlen, -⟩
  · exact h
  · exact absurd (reachedO_length_lt hQ hR) (by rw [hlen]; omega)

/-! ### The descent, semantically

The chain of `Lax3Proofs.Evaluator.tablesLocal_iff_sat`, read between
two satisfactions instead of between a table and a satisfaction. That
one change is what makes it independent of the splitter game: the
evaluator needed the win to know that its recursion's batch exists and
that its base case is reached, and neither question arises when both
sides of the equivalence are `Sat`. The batch may therefore be *the
program's own* — whatever its searches produced — and the cover the
program's own, with only the two facts the rewrites ask for: that the
cluster contains the `cap`-ball of the vertex, and that the batch is
enumerated by `Fin mb`. -/

section Descent

variable {q_top mb j : ℕ}

/-- **One level of the descent.** A tabled formula holds at a vertex of
the arena exactly when its step formula holds at the same vertex of the
cluster step's arena, under the cluster step's colouring. Semantic
locality moves the truth inside the cluster, relativization turns that
into truth over the restricted arena, and isolation turns that into
truth of the translated formula over the isolated arena — the three
links of the evaluator's chain, at the padded batch width. -/
theorem sat_step (hcap : cap = rhoMinus 0 q_top) {A : SimpleGraph (Fin n)}
    {col : Coloring n (sigL cap mb j)} {X : Set (Fin n)} (w : Fin mb → Fin n) (v : Fin n)
    {β : DistFO (sigL cap mb j) 1} (hβ : TableRank q_top β)
    (hball : ball A cap v ⊆ X) :
    Sat A col (fun _ => v) β ↔
      Sat (stepArenaP A X w) (stepColoringP cap A col X w) (fun _ => v)
        (stepFml cap mb j β) := by
  obtain ⟨hloc, k', q', hk, hsum, hq⟩ := hβ
  obtain ⟨jj, rfl⟩ : ∃ jj, k' = jj + 1 := ⟨k' - 1, by omega⟩
  have hqn : DRank jj (q' + 1) β := DRank.antidiagonal hq
  have hm : rhoMinus jj (q' + 1) ≤ cap := hcap ▸ Evaluator.rhoMinus_le_cap (by omega)
  have hp : rhoPlus (jj + 1) q' ≤ cap := hcap ▸ Evaluator.rhoPlus_le_cap (by omega)
  have hcap1 : 1 ≤ cap := Lax3Proofs.Isolate.one_le_cap_of_rhoMinus_le hm
  have hiso :
      Sat (deleteVerts A Xᶜ) (Evaluator.relColoring col X) (fun _ => v)
          (Lax3Proofs.Relativize.rel Fin.castSucc (Fin.last (sigL cap mb j)) β) ↔
        Sat (stepArenaP A X w) (stepColoringP cap A col X w) (fun _ => v)
          (stepFml cap mb j β) :=
    Lax3Proofs.Isolate.sat_iso (fun c => Evaluator.isoColoring_slotOld c)
      (fun i a => Evaluator.isoColoring_slotPd i a)
      (fun c b => Evaluator.isoColoring_slotPu c b) hcap1 _
      (Lax3Proofs.Isolate.radiiLe_of_drank
        (Lax3Proofs.Relativize.drank_rel Fin.castSucc (Fin.last _) hqn) hm hp) (fun _ => v)
  rw [← hiso, Lax3Proofs.Relativize.sat_rel (Evaluator.relColoring_castSucc col X)
    (Evaluator.relColoring_last col X)]
  exact SemLocal.sat_iff_satWithin_of_ball_subset' A col hloc hqn (fun _ => v)
    (fun _ => (ball_mono_radius A v hm).trans hball)

/-- **The descent, as the readback performs it.** A tabled formula holds
at a vertex exactly when its own boolean combination — the one
`FormulaTables.bcOf` records, which is the one the evaluator chose —
evaluates to true over the satisfactions of its local atoms at that
vertex of the cluster step's arena and the scatter values of its scatter
atoms in the same arena.

This is what the driver reads back: the local atoms are tabled one depth
down (`FormulaTables.bcLocals_subset_tablesAt_succ`), so their values are
bits of the depth-`(j+1)` tables at the vertex; the scatter atoms are
decided by `Lax3Proofs.RamScatter` over the depth-`(j+1)` table row of
their own one-variable formula
(`FormulaTables.bcBetas_subset_tablesAt_succ`). Nothing else is needed,
and in particular no splitter win. -/
theorem sat_iff_eval_step (hcap : cap = rhoMinus 0 q_top) {A : SimpleGraph (Fin n)}
    {col : Coloring n (sigL cap mb j)} {X : Set (Fin n)} (w : Fin mb → Fin n) (v : Fin n)
    {β : DistFO (sigL cap mb j) 1} (hβ : TableRank q_top β)
    (hball : ball A cap v ⊆ X) :
    Sat A col (fun _ => v) β ↔
      (bcOf q_top (stepFml cap mb j β) (hasRank_stepFml hβ)).eval
        (Sum.elim
          (fun γ => Sat (stepArenaP A X w) (stepColoringP cap A col X w) (fun _ => v) γ)
          (fun σ : ScatterSentence (sigL cap mb (j + 1)) =>
            σ.t ≤ (greedySet (stepArenaP A X w) σ.r
              {a | Sat (stepArenaP A X w) (stepColoringP cap A col X w)
                (fun _ => a) σ.β}).ncard)) := by
  refine (sat_step hcap w v hβ hball).trans
    ((sat_iff_eval_bcOf (hasRank_stepFml hβ) (stepArenaP A X w) (stepColoringP cap A col X w)
      (fun _ => v)).trans ?_)
  refine BCAlgebra.eval_congr _ ?_
  rintro (γ | σ) -
  · exact Iff.rfl
  · exact Iff.rfl

end Descent

/-! ### The sentence, semantically

The same statement at the root, at arity zero. The top sentence's local
atoms are *sentences* of distance logic, decided outright by
`Evaluator.localSentenceEval` with no arena — they are constants of the
program text — and its scatter atoms are decided over the depth-zero
tables. So the root's readback is a boolean combination of constants and
scatter flags, and no table of the root is read for anything else. -/

/-- **The root's readback is correct.** The first-order sentence holds in
the graph exactly when the boolean combination `FormulaTables.bcOf₀`
records evaluates to true over the truth values of its local atoms —
computed at construction time — and the greedy scatter values of its
scatter atoms over the graph's own colouring. -/
theorem sat_iff_eval_sentence {q_top mb : ℕ} {φ : Lax3.FirstOrder.FO 0}
    (hrank : Lax3.FirstOrder.rank φ ≤ q_top) (G : SimpleGraph (Fin n))
    (col : Coloring n (sigL cap mb 0))
    (h : ∃ q' : ℕ, q' ≤ q_top ∧
      DRank 0 q' (Reduction.toDistFO (L := sigL cap mb 0) φ) :=
      ⟨q_top, le_rfl, Reduction.drank_toDistFO φ hrank⟩) :
    Lax3.FirstOrder.Sat G Fin.elim0 φ ↔
      (bcOf₀ q_top (Reduction.toDistFO (L := sigL cap mb 0) φ) h).eval
        (Sum.elim Evaluator.localSentenceEval
          (fun σ : ScatterSentence (sigL cap mb 0) =>
            σ.t ≤ (greedySet G σ.r {a | Sat G col (fun _ => a) σ.β}).ncard)) := by
  refine (Reduction.sat_toDistFO (L := sigL cap mb 0) G col Fin.elim0 φ).symm.trans
    ((sat_iff_eval_bcOf₀ h G col Fin.elim0).trans ?_)
  refine BCAlgebra.eval_congr _ ?_
  rintro (γ | σ) hmem
  · exact (Evaluator.localSentenceEval_iff γ ((bcOf₀_spec q_top _ h).1 γ hmem).1).symm
  · exact Iff.rfl

/-! ### Reading the machine's arrays as mathematics

Two readings, used by every specification below: a colour array holds
the colour class of the vertices whose cell is nonzero, and the family
of colour arrays of a depth holds the colouring of that depth. -/

/-- The colouring the depth's colour arrays hold: the cell of colour `c`
at `v` is nonzero exactly when `v` carries `c`. -/
def colRead (n : ℕ) (C : ℕ → ℕ → ℕ) (L : ℕ) : Coloring n L :=
  fun c => {v : Fin n | C (c : ℕ) (v : ℕ) ≠ 0}

/-- Membership in a read-back colour class is the cell being nonzero. -/
theorem mem_colRead {C : ℕ → ℕ → ℕ} {L : ℕ} {c : Fin L} {v : Fin n} :
    v ∈ colRead n C L c ↔ C (c : ℕ) (v : ℕ) ≠ 0 := Iff.rfl

/-- Every array of the list is present at its declared length. This is
the whole of the memory bookkeeping a phase's precondition needs: the
sub-programs pin their own arrays in their own preconditions, and the
driver pins the per-depth families here. -/
def Sized (l : List (String × ℕ)) (σ : Env) : Prop :=
  ∀ p ∈ l, ∃ g : ℕ → ℕ, σ.arrs p.1 = arrOf p.2 g

/-- A `Sized` clause is read one array at a time. -/
theorem Sized.get {l : List (String × ℕ)} {σ : Env} (h : Sized l σ)
    {p : String × ℕ} (hp : p ∈ l) : ∃ g : ℕ → ℕ, σ.arrs p.1 = arrOf p.2 g := h p hp

/-- The length of an array a `Sized` clause names. -/
theorem Sized.length {l : List (String × ℕ)} {σ : Env} (h : Sized l σ)
    {p : String × ℕ} (hp : p ∈ l) : (σ.arrs p.1).length = p.2 := by
  obtain ⟨g, hg⟩ := h p hp
  rw [hg, length_arrOf]

/-- **A `Sized` clause survives any run**, since a run cannot change the
length of an array. -/
theorem Sized.run {B : ℕ} {c : Com} {σ σ' : Env} {K : ℕ} {l : List (String × ℕ)}
    (h : Sized l σ) (hr : Run B c σ σ' K) : Sized l σ' := fun p hp =>
  exists_arrOf ((run_length_arrs hr p.1).trans (h.length hp))

/-- **The fixed scratch arrays of a level**, at the lengths the passes
below address them at, and — for the two the breadth-first search reads
back — holding words.

Nothing in the block structure or in the masks of a depth says that the
arrays the *sub-programs* address are there, and an out-of-range store
has no derivation at all in IMP+, so a level's precondition that does
not carry this clause supports no specification for a program that
stores into any of them. The list is the union of what the passes below
ask for in their own preconditions: `RamCover.CoverPre` names `alv`,
`ord`, `dist`, `q`, `asg`, `xoff` and `xmem`, and `RamScatter`'s pass
names `alv`, `tab`, `dist`, `q` and `exc` — the last two of `dist` and
`q` as `RamScatter.Words`, which is the word clause here.

Every clause of it is preserved by every run, which is why it can be
asked of a level's exit as well as of its entry: `levelMem_run`. -/
def LevelMem (B n : ℕ) (σ : Env) : Prop :=
  Sized [("alv", n), ("tab", n), ("dist", n), ("q", n), ("exc", n), ("asg", n),
      ("ord", n), ("xoff", n + 1), ("xmem", n * n)] σ ∧
    (∀ v ∈ σ.arrs "dist", v < B) ∧ (∀ v ∈ σ.arrs "q", v < B)

/-- **The memory clause of a level survives any run.** The lengths
because a store never changes one, the two word clauses because a
bounded run stores only words. Neither is a frame condition — both hold
of arrays the passes below do write — which is what makes the levels,
and the turns of a level, compose. -/
theorem levelMem_run {B n : ℕ} {c : Com} {σ σ' : Env} {K : ℕ} (hr : Run B c σ σ' K)
    (h : LevelMem B n σ) : LevelMem B n σ' :=
  ⟨h.1.run hr, run_mem_arrs_lt hr "dist" h.2.1, run_mem_arrs_lt hr "q" h.2.2⟩

/-- The two arrays the search reads back, as `RamScatter.Words`. -/
theorem LevelMem.words {B n : ℕ} {σ : Env} (h : LevelMem B n σ) :
    RamScatter.Words B n "dist" σ ∧ RamScatter.Words B n "q" σ :=
  ⟨words_of_length (h.1.length (p := ("dist", n)) (by simp)) h.2.1,
    words_of_length (h.1.length (p := ("q", n)) (by simp)) h.2.2⟩

/-! ### The names

Every per-depth object of the driver is addressed by a name built at
construction time from the depth, and — for the tables, the colours and
the scatter flags — from a position. The names are pairwise distinct and
distinct from the fixed names the sub-programs address, which is what
lets a call be preceded by a copy and followed by nothing. -/

/-- The mask of the work arena at depth `j`: the arena the tables of that
depth are about. -/
def alvName (j : ℕ) : String := "alv" ++ toString j

/-- The mask of the game arena at depth `j`: the position of the splitter
play, which the work arena is a subgraph of. -/
def gamName (j : ℕ) : String := "gam" ++ toString j

/-- The indicator of the cluster currently being processed at depth `j`. -/
def cluName (j : ℕ) : String := "clu" ++ toString j

/-- The mask of the work arena restricted to the current cluster, in
which the distance profiles are measured. -/
def resName (j : ℕ) : String := "res" ++ toString j

/-- The indicator of the ball the current round restricts the game arena
to. -/
def balName (j : ℕ) : String := "bal" ++ toString j

/-- The other half of the ball's ping-pong. `expandCom` reads its source
array at *every* vertex of a row while it writes its destination cell by
cell, so a chain of expansions that wrote into the array it was reading
would see its own marks: one pass would then propagate along a whole
path rather than along one edge, and the chain would mark a superset of
the ball it is supposed to build. The chain therefore alternates between
two names, and — the radius being `2 · cap`, an even number — ends where
it started. -/
def balAltName (j : ℕ) : String := "blt" ++ toString j

/-- The indicator of the batch the splitter strategy isolates at depth
`j`. -/
def batName (j : ℕ) : String := "bat" ++ toString j

/-- The connector vertex played at depth `j`: the centre of the cluster
being processed. -/
def ctrName (j : ℕ) : String := "ctr" ++ toString j

/-- The array of the colour `c` at depth `j`, for `c < sigL cap mb j`. -/
def colName (j c : ℕ) : String := "co" ++ toString j ++ "_" ++ toString c

/-- The table array of the formula at position `i` of depth `j`. -/
def tabName (j i : ℕ) : String := "ta" ++ toString j ++ "_" ++ toString i

/-- The scatter flag of the atom at position `k` of the boolean
combination of the formula at position `i` of depth `j`. -/
def flgName (j i k : ℕ) : String := "fl" ++ toString j ++ "_" ++ toString i ++ "_" ++ toString k

/-- The scatter flag of the atom at position `k` of the top sentence's
boolean combination. -/
def rootFlgName (k : ℕ) : String := "rf" ++ toString k

/-- The environment entry `i` of the base case's evaluation. -/
def envName (i : ℕ) : String := "ev" ++ toString i

/-- **The memory clause of the decode**: the four arrays it writes, at
the lengths it writes them at. The decode runs before any level, so it
is the one phase whose memory clause is not a level's. -/
def DecodeMem (n ns : ℕ) (σ : Env) : Prop :=
  (σ.arrs "off").length = n + 1 ∧ (σ.arrs "tgt").length = ns ∧
    (σ.arrs (alvName 0)).length = n ∧ (σ.arrs (gamName 0)).length = n

/-! ### Plumbing

Four flat passes the driver writes itself, since none of them belongs to
any of the sub-programs: a fill, a copy, and the two mask operations. All
four are the kit's array pass with a different cell expression, so their
walks are one application of `Fill.loop_spec` apiece. -/

/-- A flat pass over the first `bnd` cells of an array, writing the value
of `e` into each. -/
def fillUpto (a : String) (bnd e : Expr) : Com :=
  .seq (.assign "i" (.lit 0)) (.while (.lt (.var "i") bnd) (Fill.put a "i" e))

/-- The same over the whole carrier. -/
def fillCom (a : String) (e : Expr) : Com := fillUpto a (.var "n") e

/-- Copy the first `bnd` cells of one array into another. -/
def copyUpto (src dst : String) (bnd : Expr) : Com := fillUpto dst bnd (.get src (.var "i"))

/-- Copy one array of the carrier's length into another: the whole of the
driver's calling convention, since every sub-program addresses fixed
array names. -/
def copyCom (src dst : String) : Com := copyUpto src dst (.var "n")

/-- The pointwise conjunction of two masks, into a third. -/
def andCom (a b dst : String) : Com :=
  fillCom dst (.mul (.get a (.var "i")) (.get b (.var "i")))

/-- The first mask with everything the second marks killed. -/
def subCom (a b dst : String) : Com :=
  fillCom dst (.mul (.get a (.var "i")) (.sub (.lit 1) (.get b (.var "i"))))

/-- Sequence a command over a list, giving each entry its position. -/
def foldIdx {X : Type*} (f : ℕ → X → Com) : ℕ → List X → Com
  | _, [] => .skip
  | i, x :: xs => .seq (f i x) (foldIdx f (i + 1) xs)

/-- Sequence a command over the first `m` numbers. -/
def foldRange (f : ℕ → Com) (m : ℕ) : Com :=
  (List.range m).foldr (fun a c => .seq (f a) c) .skip

/-! ### Reachability by expansion

Both profile families of the isolation step are `b`-neighbourhoods of a
vertex set — of a batch vertex for `slotPd`, of a colour class for
`slotPu` — and the radius is a construction-time constant. So the driver
does not search for them: it expands a set by one step at a time, `cap`
times, which is one flat pass over the block structure per step and no
queue at all. The searches of `Lax3Proofs.RamBfs` are left for the two
places that really need shortest paths — the cover and the splitter's
paths — and for the scatter pass, which owns its own. -/

/-- One slot of the row being scanned: an alive neighbour that the source
set marks sets the hit flag. -/
def expandSlot (msk src : String) : Com :=
  .seq (.assign "w" (.get "tgt" (.var "j")))
    (.seq (.ite (.lt (.lit 0) (.get msk (.var "w")))
            (.ite (.lt (.lit 0) (.get src (.var "w"))) (.assign "hit" (.lit 1)) .skip)
            .skip)
      (.assign "j" (.add (.var "j") (.lit 1))))

/-- One vertex of the expansion: it stays marked if it was, and becomes
marked if it is alive and some alive neighbour of it was. -/
def expandStep (msk src dst : String) : Com :=
  .seq (.assign "hit" (.get src (.var "z")))
    (.seq (.ite (.lt (.lit 0) (.get msk (.var "z")))
            (.seq (Csr.loadRow "off" "z" "j" "jend")
              (Csr.scan "j" "jend" (expandSlot msk src)))
            .skip)
      (.seq (.store dst (.var "z") (.var "hit"))
        (.assign "z" (.add (.var "z") (.lit 1)))))

/-- **One step of neighbourhood expansion** of a vertex set in the arena
the mask cuts out. -/
def expandCom (msk src dst : String) : Com :=
  .seq (.assign "z" (.lit 0)) (.while (.lt (.var "z") (.var "n")) (expandStep msk src dst))

/-- The chain of expansions: `nm a` holds the `a`-neighbourhood of what
`nm 0` was set to. The names must be pairwise distinct at consecutive
stages, since a step reads all of its source while it writes its
destination. -/
def chainCom (msk : String) (nm : ℕ → String) (r : ℕ) : Com :=
  foldRange (fun a => expandCom msk (nm a) (nm (a + 1))) r

/-! ### The colour arrays of the next depth

`FormulaTables` pins the packing of the depth-`(j+1)` palette: the
incoming colours, one slot per padded batch entry and capped distance,
and one per incoming colour and capped distance. The three slot maps are
computable, so the driver addresses its colour arrays by the *numeric
value* of the slot and no packing arithmetic appears in the program text
at all. -/

/-- The position of the incoming colour `c` in the depth-`(j+1)`
palette. -/
def oldIdx (cap mb j c : ℕ) : ℕ :=
  ((oldSlots cap mb j ⟨min c (sigL cap mb j), by omega⟩ : Fin (sigL cap mb (j + 1))) : ℕ)

/-- The position of the profile of the padded batch entry `i` at radius
`a`. -/
def pdIdx (cap mb j : ℕ) (i : Fin mb) (a : ℕ) : ℕ :=
  ((pdSlots cap mb j i ⟨min a cap, by omega⟩ : Fin (sigL cap mb (j + 1))) : ℕ)

/-- The position of the profile of the colour class `c` at radius `b`. -/
def puIdx (cap mb j c b : ℕ) : ℕ :=
  ((puSlots cap mb j ⟨min c (sigL cap mb j), by omega⟩ ⟨min b cap, by omega⟩ :
    Fin (sigL cap mb (j + 1))) : ℕ)

/-- **The relativized colours.** Every incoming colour intersected with
the cluster, and the cluster itself in the marker slot. -/
def oldCom (cap mb j : ℕ) : Com :=
  .seq (foldRange (fun c =>
      andCom (colName j c) (cluName j) (colName (j + 1) (oldIdx cap mb j c)))
    (sigL cap mb j))
    (copyCom (cluName j) (colName (j + 1) (oldIdx cap mb j (sigL cap mb j))))

/-- **The batch profiles.** The singleton of each padded batch entry,
expanded `cap` times in the cluster-restricted arena. -/
def pdCom (cap mb j : ℕ) : Com :=
  (List.finRange mb).foldr (fun i c =>
      .seq (.seq (fillCom (colName (j + 1) (pdIdx cap mb j i 0)) (.lit 0))
        (.seq (.store (colName (j + 1) (pdIdx cap mb j i 0)) (.get "wa" (.lit (i : ℕ)))
            (.lit 1))
          (chainCom (resName j) (fun a => colName (j + 1) (pdIdx cap mb j i a)) cap))) c)
    .skip

/-- **The colour profiles.** Every relativized colour class, expanded
`cap` times in the same arena. -/
def puCom (cap mb j : ℕ) : Com :=
  foldRange (fun c =>
    .seq (copyCom (colName (j + 1) (oldIdx cap mb j c)) (colName (j + 1) (puIdx cap mb j c 0)))
      (chainCom (resName j) (fun b => colName (j + 1) (puIdx cap mb j c b)) cap))
    (sigL cap mb j + 1)

/-- **The colouring of one cluster step**, the three slot families
together: this is `Evaluator.stepColoring`'s three equations, written
out at the padded packing. -/
def colourCom (cap mb j : ℕ) : Com :=
  .seq (oldCom cap mb j) (.seq (pdCom cap mb j) (puCom cap mb j))

/-! ### The splitter batch

`SplitterWinOracle.genSetO` is the connector itself together with, for
every earlier connector, the oracle's path from it to the new one *taken
in the arena that round was played in*; `batchO` cuts that down to the
ball the round restricts to. The driver has both: the earlier connectors
are the scalars `ctr a`, and the arenas they were played in are the game
masks `gam a`, which is exactly why the game masks are kept. The oracle
is instantiated at the path `Lax3Proofs.RamBfsPaths.bfsPathCom` leaves in
its buffer, by the recipe in that file's final section. -/

/-- Mark the cells of the path buffer in the batch indicator: the buffer
holds `pl + 1` vertices. -/
def markPath (bat : String) : Com :=
  .seq (.assign "i" (.lit 0))
    (.seq (.assign "plen" (.add (.var "pl") (.lit 1)))
      (.while (.lt (.var "i") (.var "plen"))
        (.seq (.store bat (.get "path" (.var "i")) (.lit 1))
          (.assign "i" (.add (.var "i") (.lit 1))))))

/-- One earlier round's contribution: the path from its connector to the
current one, searched in the arena that round was played in. -/
def ancestorStep (cap j a : ℕ) : Com :=
  .seq (.assign "src" (.var (ctrName a)))
    (.seq (.assign "tv" (.var (ctrName j)))
      (.seq (copyCom (gamName a) "alv")
        (.seq (RamBfsPaths.bfsPathCom (2 * cap)) (markPath (batName j)))))

/-- **The batch of the round**: the connector together with the oracle's
paths from every earlier connector, cut down to the ball the round
restricts to. -/
def batchCom (cap j : ℕ) : Com :=
  .seq (fillCom (batName j) (.lit 0))
    (.seq (.store (batName j) (.var (ctrName j)) (.lit 1))
      (.seq (foldRange (fun a => ancestorStep cap j a) j)
        (andCom (batName j) (balName j) (batName j))))

/-- The padded enumeration of the batch, as an array of exactly `mb`
entries: the batch in vertex order, then the first entry repeated. The
batch is never empty — it contains its own connector — so the repetition
is well defined, and `FormulaTables.range_comp_of_surjective` is why it
costs the isolation rewrite nothing. -/
def enumBatch (bat : String) (mb : ℕ) : Com :=
  .seq (.assign "bc" (.lit 0))
    (.seq (.assign "z" (.lit 0))
      (.seq (.while (.lt (.var "z") (.var "n"))
              (.seq (.ite (.lt (.lit 0) (.get bat (.var "z")))
                      (.seq (.store "wa" (.var "bc") (.var "z"))
                        (.assign "bc" (.add (.var "bc") (.lit 1))))
                      .skip)
                (.assign "z" (.add (.var "z") (.lit 1)))))
        (.seq (.assign "k" (.var "bc"))
          (.while (.lt (.var "k") (.lit mb))
            (.seq (.store "wa" (.var "k") (.get "wa" (.lit 0)))
              (.assign "k" (.add (.var "k") (.lit 1))))))))

/-! ### The base case

At depth `ℓ` the arena is edgeless, and `Lax3Proofs.BotEval` says what
satisfaction is there: adjacency is never satisfied, both distance atoms
are equality tests, a local quantifier is a finite disjunction over the
entries its guard set names, and an unrestricted quantifier is a
disjunction over the entries of the environment together with one
representative of each colour row realized off it.

So the base program is generated *by recursion on the formula*, which is
a construction-time object: every case above is a piece of program text,
and the two quantifiers are loops over an array the enclosing text
loaded. Fresh names come from the output scalar's own name, extended by
one character per level, so the generated text never has two live
variables of the same name. -/

/-- The truncated-arithmetic equality test of two cells: `1` when they
agree and `0` when they do not. -/
def eqBitExpr (a b : Expr) : Expr := .sub (.lit 1) (.add (.sub a b) (.sub b a))

/-- The truncated-arithmetic disjunction of two bits. -/
def orBitExpr (a b : Expr) : Expr :=
  .sub (.lit 1) (.mul (.sub (.lit 1) a) (.sub (.lit 1) b))

/-- Two vertices carry the same colours: the product over the depth's
colour arrays of the equality of their cells. The palette is a
construction-time constant, so this is one expression and not a loop. -/
def rowEqExpr (j L : ℕ) (x y : String) : Expr :=
  (List.range L).foldr
    (fun c e => .mul (eqBitExpr (.get (colName j c) (.var x)) (.get (colName j c) (.var y))) e)
    (.lit 1)

/-- **The representative pass.** One vertex per colour row: a vertex is
recorded when it matches none of the rows already recorded. What
`Lax3Proofs.BotEval.exists_offRepr` asks of the result is exactly that
every vertex has a same-row companion among the records, which a scan
that only skips matched vertices delivers. -/
def reprCom (j L : ℕ) : Com :=
  .seq (.assign "rp" (.lit 0))
    (.seq (.assign "z" (.lit 0))
      (.while (.lt (.var "z") (.var "n"))
        (.seq (.assign "seen" (.lit 0))
          (.seq (.assign "rw" (.lit 0))
            (.seq (.while (.lt (.var "rw") (.var "rp"))
                    (.seq (.assign "rv" (.get "rep" (.var "rw")))
                      (.seq (.assign "seen"
                          (orBitExpr (.var "seen") (rowEqExpr j L "z" "rv")))
                        (.assign "rw" (.add (.var "rw") (.lit 1))))))
              (.seq (.ite (.lt (.lit 0) (.var "seen")) .skip
                      (.seq (.store "rep" (.var "rp") (.var "z"))
                        (.assign "rp" (.add (.var "rp") (.lit 1)))))
                (.assign "z" (.add (.var "z") (.lit 1)))))))))

/-- Load the entries the guard set names into the node's own candidate
array. The guard set is a construction-time `Finset`, so this is a
straight line of stores. -/
def guardLoad {k : ℕ} (g : List (Fin k)) (arr cnt : String) : Com :=
  .seq (foldIdx (fun p i => .store arr (.lit p) (.var (envName (i : ℕ)))) 0 g)
    (.assign cnt (.lit g.length))

/-- Load the whole environment and then the representatives into the
node's own candidate array: the two families a witness search on an
edgeless arena has to try. -/
def envLoad (k : ℕ) (arr cnt : String) : Com :=
  .seq (foldRange (fun i => .store arr (.lit i) (.var (envName i))) k)
    (.seq (.assign cnt (.lit k))
      (.seq (.assign "rw" (.lit 0))
        (.while (.lt (.var "rw") (.var "rp"))
          (.seq (.store arr (.var cnt) (.get "rep" (.var "rw")))
            (.seq (.assign cnt (.add (.var cnt) (.lit 1)))
              (.assign "rw" (.add (.var "rw") (.lit 1))))))))

open Classical in
/-- **The base evaluator, as program text.** `botCom j ψ out` leaves in
the scalar `out` the truth value of `ψ` on the edgeless arena, at the
environment held in the scalars `envName 0 … envName (k-1)` and the
colouring held in the colour arrays of depth `j`.

Each case is one of `Lax3Proofs.BotEval`'s lemmas read as code:
`sat_adj_bot`, `sat_eq_bot`, `sat_color_bot`, `sat_distLe_bot` and
`sat_distColorLt_bot` for the atoms, `sat_exL_bot` for the local
quantifier, and `sat_exU_bot_of_repr` for the unrestricted one. -/
noncomputable def botCom (jd : ℕ) {L : ℕ} : {k : ℕ} → DistFO L k → String → Com
  | _, .adj _ _, out => .assign out (.lit 0)
  | _, .eq i j, out =>
      .ite (.eq (.var (envName (i : ℕ))) (.var (envName (j : ℕ))))
        (.assign out (.lit 1)) (.assign out (.lit 0))
  | _, .color c i, out =>
      .ite (.lt (.lit 0) (.get (colName jd (c : ℕ)) (.var (envName (i : ℕ)))))
        (.assign out (.lit 1)) (.assign out (.lit 0))
  | _, .distLe _ i j, out =>
      .ite (.eq (.var (envName (i : ℕ))) (.var (envName (j : ℕ))))
        (.assign out (.lit 1)) (.assign out (.lit 0))
  | _, .distColorLt r c i, out =>
      if r = 0 then .assign out (.lit 0)
      else .ite (.lt (.lit 0) (.get (colName jd (c : ℕ)) (.var (envName (i : ℕ)))))
        (.assign out (.lit 1)) (.assign out (.lit 0))
  | _, .not ψ, out =>
      .seq (botCom jd ψ (out ++ "a")) (.assign out (.sub (.lit 1) (.var (out ++ "a"))))
  | _, .and ψ χ, out =>
      .seq (botCom jd ψ (out ++ "a"))
        (.seq (botCom jd χ (out ++ "b"))
          (.assign out (.mul (.var (out ++ "a")) (.var (out ++ "b")))))
  | k, .exU ψ, out =>
      .seq (envLoad k (out ++ "g") (out ++ "m"))
        (.seq (.assign out (.lit 0))
          (.seq (.assign (out ++ "w") (.lit 0))
            (.while (.lt (.var (out ++ "w")) (.var (out ++ "m")))
              (.seq (.assign (envName k) (.get (out ++ "g") (.var (out ++ "w"))))
                (.seq (botCom jd ψ (out ++ "a"))
                  (.seq (.assign out (orBitExpr (.var out) (.var (out ++ "a"))))
                    (.assign (out ++ "w") (.add (.var (out ++ "w")) (.lit 1)))))))))
  | k, .exL _ g ψ, out =>
      .seq (guardLoad g.toList (out ++ "g") (out ++ "m"))
        (.seq (.assign out (.lit 0))
          (.seq (.assign (out ++ "w") (.lit 0))
            (.while (.lt (.var (out ++ "w")) (.var (out ++ "m")))
              (.seq (.assign (envName k) (.get (out ++ "g") (.var (out ++ "w"))))
                (.seq (botCom jd ψ (out ++ "a"))
                  (.seq (.assign out (orBitExpr (.var out) (.var (out ++ "a"))))
                    (.assign (out ++ "w") (.add (.var (out ++ "w")) (.lit 1)))))))))

/-- **The base case.** Build the representative system once, then walk
the vertices, evaluating every formula of the depth's table at each. -/
noncomputable def baseCom (q_top cap mb ℓ : ℕ) (φ : Lax3.FirstOrder.FO 0) : Com :=
  .seq (reprCom ℓ (sigL cap mb ℓ))
    (.seq (.assign "z" (.lit 0))
      (.while (.lt (.var "z") (.var "n"))
        (.seq (.assign (envName 0) (.var "z"))
          (.seq (foldIdx (fun i β =>
              .seq (botCom ℓ β "bb") (.store (tabName ℓ i) (.var "z") (.var "bb"))) 0
              (tablesAt q_top cap mb φ ℓ))
            (.assign "z" (.add (.var "z") (.lit 1)))))))

/-! ### The ordering pass

The cover is taken along the ordering the elimination engine of
`Lax3Proofs.RamElim` produces on the `R`-times augmented arena, which is
what `Lax3Proofs.CoverDegree.exists_cover_degree` bounds the degree of.
The pass is therefore three programs in a row: one elimination to give
the arena an orientation, `R` rounds of `Lax3Proofs.RamAugment` with the
copy-and-zero bookkeeping its composition surface describes between
them, and one more elimination on the last round's graph — after which
the rank array is inverted into the order array the cover pass reads. -/

/-- Invert the rank array into the order array: the vertex of rank `c`
goes to position `c`, which is `RamCover.OrdersBy` read as a program. -/
def ordCom : Com :=
  .seq (.assign "z" (.lit 0))
    (.while (.lt (.var "z") (.var "n"))
      (.seq (.store "ord" (.get "rnk" (.var "z")) (.var "z"))
        (.assign "z" (.add (.var "z") (.lit 1)))))

/-- The bookkeeping between two augmentation rounds: the block structure
the round wrote becomes the one the next round reads, and the
accumulators and stamps are zeroed again. This is the composition
surface of `Lax3Proofs.RamAugment`, written out. -/
def augRelinkCom (W : ℕ) : Com :=
  .seq (copyUpto "noff" "doff" (.add (.var "n") (.lit 1)))
    (.seq (copyUpto "ntg" "dtg" (.lit W))
      (.seq (fillUpto "ooff" (.add (.var "n") (.lit 1)) (.lit 0))
        (.seq (fillUpto "off" (.add (.var "n") (.lit 1)) (.lit 0))
          (.seq (fillUpto "noff" (.add (.var "n") (.lit 1)) (.lit 0))
            (.seq (fillCom "stf" (.lit 0))
              (.seq (fillCom "sta" (.lit 0))
                (.seq (fillCom "std" (.lit 0)) (fillCom "ste" (.lit 0)))))))))

/-- The symmetric closure of the last round's in-lists, in
compressed-row form: what the final elimination is run on. -/
def symCom : Com :=
  .seq (fillUpto "off" (.add (.var "n") (.lit 1)) (.lit 0)) (fillCom "tgt" (.lit 0))

/-- **The ordering pass at depth `j`.** One elimination to orient the
arena, `R` augmentation rounds, the symmetric closure of the result, a
final elimination, and the inversion of its rank array. -/
def orderCom (R W j : ℕ) : Com :=
  .seq (copyCom (alvName j) "alv")
    (.seq RamElim.elimCom
      (.seq (copyUpto "ioff" "doff" (.add (.var "n") (.lit 1)))
        (.seq (copyUpto "itg" "dtg" (.lit W))
          (.seq (foldRange (fun _ => .seq RamAugment.augCom (augRelinkCom W)) R)
            (.seq symCom
              (.seq (fillCom "alv" (.lit 1))
                (.seq RamElim.elimCom ordCom)))))))

/-! ### One cluster

The turn of the loop over the centres the cover produced. It writes the
depth-`(j + 1)` state — the two masks, the padded batch enumeration and
the whole colour palette — runs the nested driver, decides the scatter
atoms of every tabled formula over the depth-`(j + 1)` tables, and reads
the boolean combinations back into the depth-`j` tables at the vertices
this cluster was assigned.

The order of the two restrictions is `Evaluator.stepArena`'s: the cluster
first, the batch second. The profiles are measured in the
*cluster-restricted* arena and not in the isolated one, which is what
`Evaluator.isoColoring`'s three equations say and where `resName j`
comes from. -/

/-- The two names the ball's expansion chain alternates between: the
even stages are the ball's own array, the odd ones the scratch half. -/
def ballStage (j : ℕ) : ℕ → String :=
  fun a => if a % 2 = 0 then balName j else balAltName j

/-- The chain begins and — the radius being even — ends at the ball's
own array. -/
theorem ballStage_zero (j : ℕ) : ballStage j 0 = balName j := by
  rw [ballStage]; simp

theorem ballStage_two_mul (j a : ℕ) : ballStage j (2 * a) = balName j := by
  rw [ballStage]
  simp [Nat.mul_mod_right]

/-- Consecutive stages are different arrays, which is the whole point of
the alternation. -/
theorem ballStage_ne (j a : ℕ) : ballStage j a ≠ ballStage j (a + 1) := by
  have hne : balName j ≠ balAltName j := by
    simp [balName, balAltName, String.ext_iff]
  simp only [ballStage]
  rcases Nat.even_or_odd a with h | h
  · have h₀ : a % 2 = 0 := Nat.even_iff.mp h
    rw [if_pos h₀, if_neg (by omega)]
    exact hne
  · have h₁ : a % 2 = 1 := Nat.odd_iff.mp h
    rw [if_neg (by omega), if_pos (by omega)]
    exact fun hc => hne hc.symm

/-- Materialize the indicator of the cluster at position `c` out of the
compressed-row cluster arena the cover pass left. -/
def clusterLoad (j : ℕ) : Com :=
  .seq (fillCom (cluName j) (.lit 0))
    (.seq (Csr.loadRow "xoff" "c" "p" "pend")
      (Csr.scan "p" "pend"
        (.seq (.store (cluName j) (.get "xmem" (.var "p")) (.lit 1))
          (.assign "p" (.add (.var "p") (.lit 1))))))

/-- The state of the next depth: the ball of the round in the game
arena, the batch, and the two masks the cluster step produces. -/
def descendCom (cap j : ℕ) : Com :=
  .seq (.assign (ctrName j) (.get "ord" (.var "c")))
    (.seq (clusterLoad j)
      (.seq (andCom (alvName j) (cluName j) (resName j))
        (.seq (.seq (fillCom (balName j) (.lit 0))
            (.seq (.store (balName j) (.var (ctrName j)) (.lit 1))
              (chainCom (gamName j) (ballStage j) (2 * cap))))
          (.seq (batchCom cap j)
            (.seq (subCom (resName j) (batName j) (alvName (j + 1)))
              (.seq (andCom (gamName j) (balName j) (gamName (j + 1)))
                (subCom (gamName (j + 1)) (batName j) (gamName (j + 1)))))))))

open Classical in
/-- The scatter atoms of one tabled formula, decided over the
depth-`(j + 1)` tables in the cluster arena. -/
noncomputable def scatterCom (q_top cap mb : ℕ) (φ : Lax3.FirstOrder.FO 0) (j i : ℕ)
    (β : DistFO (sigL cap mb j) 1) : Com :=
  foldIdx (fun k σ =>
      .seq (copyCom (alvName (j + 1)) "alv")
        (.seq (copyCom (tabName (j + 1) (posOf σ.β (tablesAt q_top cap mb φ (j + 1)))) "tab")
          (.seq (RamScatter.scatterCom σ.r σ.t) (.assign (flgName j i k) (.var "flag")))))
    0 (bcAtomsOf q_top (stepFml cap mb j β)).2

open Classical in
/-- The value of a boolean combination, as an expression over the
valuations of its atoms. Every atom of the driver's combinations is a
bit, so negation is a truncated subtraction and conjunction a
product. -/
noncomputable def bcExpr {α : Type*} (val : α → Expr) : BC α → Expr
  | .atom a => val a
  | .tru => .lit 1
  | .not b => .sub (.lit 1) (bcExpr val b)
  | .and b c => .mul (bcExpr val b) (bcExpr val c)

open Classical in
/-- The valuation of the atoms of the formula at position `i` of depth
`j`: a local atom is a bit of the depth-`(j + 1)` table at the vertex the
readback stands on, a scatter atom is the flag the scatter pass left. -/
noncomputable def atomExpr (q_top cap mb : ℕ) (φ : Lax3.FirstOrder.FO 0) (j i : ℕ)
    (β : DistFO (sigL cap mb j) 1) :
    DistFO (sigL cap mb (j + 1)) 1 ⊕ ScatterSentence (sigL cap mb (j + 1)) → Expr
  | .inl γ => .get (tabName (j + 1) (posOf γ (tablesAt q_top cap mb φ (j + 1)))) (.var "z")
  | .inr σ => .var (flgName j i (posOf σ (bcAtomsOf q_top (stepFml cap mb j β)).2))

open Classical in
/-- **The readback.** Walk the vertices this cluster was assigned and
write, for every tabled formula, the value of its own boolean
combination. -/
noncomputable def readbackCom (q_top cap mb : ℕ) (φ : Lax3.FirstOrder.FO 0) (j : ℕ) : Com :=
  .seq (.assign "z" (.lit 0))
    (.while (.lt (.var "z") (.var "n"))
      (.seq (.ite (.eq (.get "asg" (.var "z")) (.var "c"))
              (foldIdx (fun i β =>
                  .store (tabName j i) (.var "z")
                    (if h : ∃ q' : ℕ, q' + 1 ≤ q_top ∧ DRank 1 q' (stepFml cap mb j β) then
                      bcExpr (atomExpr q_top cap mb φ j i β) (bcOf q_top (stepFml cap mb j β) h)
                    else .lit 0)) 0
                (tablesAt q_top cap mb φ j))
              .skip)
        (.assign "z" (.add (.var "z") (.lit 1)))))

open Classical in
/-- **One cluster.** The descent, the padded enumeration, the colouring,
the nested driver, the scatter atoms and the readback. -/
noncomputable def clusterCom (q_top cap mb : ℕ) (φ : Lax3.FirstOrder.FO 0) (j : ℕ)
    (inner : Com) : Com :=
  .seq (descendCom cap j)
    (.seq (enumBatch (batName j) mb)
      (.seq (colourCom cap mb j)
        (.seq inner
          (.seq (foldIdx (fun i β => scatterCom q_top cap mb φ j i β) 0
              (tablesAt q_top cap mb φ j))
            (readbackCom q_top cap mb φ j)))))

/-! ### The level, and the recursion

`driverAt j` is the ordering pass, the cover pass, and the loop over the
centres the cover produced with the nested `driverAt (j + 1)` inside it.
The recursion is on the fuel `ℓ - j`, which is the round budget of the
splitter game still to spend; at zero the base case runs, and at zero the
arena is edgeless by `eq_bot_of_playOk_full`. -/

open Classical in
/-- The driver at depth `j`, by downward recursion on the remaining
budget. -/
noncomputable def driverAux (q_top cap mb R ℓ W : ℕ) (φ : Lax3.FirstOrder.FO 0) :
    ℕ → ℕ → Com
  | 0, j => baseCom q_top cap mb j φ
  | f + 1, j =>
      .seq (orderCom R W j)
        (.seq (copyCom (alvName j) "alv")
          (.seq (RamCover.coverCom cap)
            (.seq (.assign "c" (.lit 0))
              (.while (.lt (.var "c") (.var "n"))
                (.seq (clusterCom q_top cap mb φ j
                    (driverAux q_top cap mb R ℓ W φ f (j + 1)))
                  (.assign "c" (.add (.var "c") (.lit 1))))))))

open Classical in
/-- **The driver at depth `j`.** The fuel is the budget still to spend;
`driverAt ℓ` is the base case. -/
noncomputable def driverAt (q_top cap mb R ℓ W : ℕ) (φ : Lax3.FirstOrder.FO 0) (j : ℕ) :
    Com :=
  driverAux q_top cap mb R ℓ W φ (ℓ - j) j

/-- The base case is what the driver runs at the bottom. -/
theorem driverAt_bot (q_top cap mb R ℓ W : ℕ) (φ : Lax3.FirstOrder.FO 0) :
    driverAt q_top cap mb R ℓ W φ ℓ = baseCom q_top cap mb ℓ φ := by
  rw [driverAt, Nat.sub_self, driverAux]

/-- Above the bottom the driver is a level. -/
theorem driverAt_succ (q_top cap mb R ℓ W : ℕ) (φ : Lax3.FirstOrder.FO 0) {j : ℕ}
    (hj : j < ℓ) :
    driverAt q_top cap mb R ℓ W φ j =
      .seq (orderCom R W j)
        (.seq (copyCom (alvName j) "alv")
          (.seq (RamCover.coverCom cap)
            (.seq (.assign "c" (.lit 0))
              (.while (.lt (.var "c") (.var "n"))
                (.seq (clusterCom q_top cap mb φ j
                    (driverAt q_top cap mb R ℓ W φ (j + 1)))
                  (.assign "c" (.add (.var "c") (.lit 1)))))))) := by
  obtain ⟨f, hf⟩ : ∃ f, ℓ - j = f + 1 := ⟨ℓ - j - 1, by omega⟩
  rw [driverAt, hf, driverAux, driverAt, show ℓ - (j + 1) = f by omega]

/-! ### The root

The input decode, the all-alive mask, the driver at depth zero, and the
sentence readback. The sentence's local atoms are *sentences*, which
`Evaluator.localSentenceEval` decides with no arena at all, so they are
literal stores; its scatter atoms are decided over the depth-zero tables
by the scatter pass; and the boolean combination of the two is the one
bit the program writes. -/

/-- The decode of the tape encoding into the block structure: the two
counts, then the two arrays, in the order `Lax11.GraphEncoding` puts
them on the tape. This is `Lax11Proofs.CC`'s reading phase. -/
def readLoop (a lim : String) : Com :=
  .seq (.assign "i" (.lit 0))
    (.while (.lt (.var "i") (.var lim))
      (.seq (.read "t")
        (.seq (.store a (.var "i") (.var "t"))
          (.assign "i" (.add (.var "i") (.lit 1))))))

/-- **The decode.** Read the encoding into `off` and `tgt`, and open the
root arena with everything alive. -/
def decodeCom : Com :=
  .seq (.read "n")
    (.seq (.read "m")
      (.seq (.assign "len" (.add (.var "n") (.lit 1)))
        (.seq (readLoop "off" "len")
          (.seq (.assign "len" (.add (.var "m") (.var "m")))
            (.seq (readLoop "tgt" "len")
              (.seq (fillCom (alvName 0) (.lit 1)) (fillCom (gamName 0) (.lit 1))))))))

open Classical in
/-- The scatter atoms of the top sentence, decided over the depth-zero
tables in the root arena. -/
noncomputable def rootScatterCom (q_top cap mb : ℕ) (φ : Lax3.FirstOrder.FO 0) : Com :=
  foldIdx (fun k σ =>
      .seq (copyCom (alvName 0) "alv")
        (.seq (copyCom (tabName 0 (posOf σ.β (tablesAt q_top cap mb φ 0))) "tab")
          (.seq (RamScatter.scatterCom σ.r σ.t) (.assign (rootFlgName k) (.var "flag")))))
    0 (bcAtomsOf₀ q_top (Reduction.toDistFO (L := sigL cap mb 0) φ)).2

open Classical in
/-- The valuation of the top sentence's atoms: a local atom is the
constant `Evaluator.localSentenceEval` decides at construction time, a
scatter atom is the flag the root scatter pass left. -/
noncomputable def rootAtomExpr (q_top cap mb : ℕ) (φ : Lax3.FirstOrder.FO 0) :
    DistFO (sigL cap mb 0) 0 ⊕ ScatterSentence (sigL cap mb 0) → Expr
  | .inl γ => if Evaluator.localSentenceEval γ then .lit 1 else .lit 0
  | .inr σ =>
      .var (rootFlgName
        (posOf σ (bcAtomsOf₀ q_top (Reduction.toDistFO (L := sigL cap mb 0) φ)).2))

open Classical in
/-- **The sentence readback.** The boolean combination of the constants
and the flags, written to the output tape. -/
noncomputable def sentenceCom (q_top cap mb : ℕ) (φ : Lax3.FirstOrder.FO 0) : Com :=
  .seq (rootScatterCom q_top cap mb φ)
    (.write
      (if h : ∃ q' : ℕ, q' ≤ q_top ∧
          DRank 0 q' (Reduction.toDistFO (L := sigL cap mb 0) φ) then
        bcExpr (rootAtomExpr q_top cap mb φ)
          (bcOf₀ q_top (Reduction.toDistFO (L := sigL cap mb 0) φ) h)
      else .lit 0))

open Classical in
/-- **The whole program**: decode, drive, decide. -/
noncomputable def driverRoot (q_top cap mb R ℓ W : ℕ) (φ : Lax3.FirstOrder.FO 0) : Com :=
  .seq decodeCom
    (.seq (driverAt q_top cap mb R ℓ W φ 0) (sentenceCom q_top cap mb φ))

/-! ### The invariant of a level

What a level owes: the bits of its tables are the truth values of its
formulas at the arena its mask cuts out, under the colouring its colour
arrays hold. This is `Evaluator.tablesLocal_iff_sat`'s conclusion at
program data, with the evaluator's table replaced by the machine's.

The domain is the whole carrier. The readback of a level writes the bit
of a vertex during the turn of the cluster that vertex was assigned to,
and `RamCover.CoverOut.asg_lt` says every vertex is assigned, so the
turns of the loop partition the carrier and the level's postcondition is
about all of it. -/

/-- **The table invariant at depth `j`.**

The cells are asked to be *bits* and not merely nonzero-or-not:
`bcExpr` is truncated arithmetic, a negation is `1 - u` and a
conjunction is a product, so the readback of the depth above reads
these cells as numbers and not only as truth values. Every pass that
writes a table writes a bit, so this is a clause missing from those
passes' postconditions rather than a property missing from the
program. -/
def TableInv (q_top cap mb : ℕ) (φ : Lax3.FirstOrder.FO 0) {n : ℕ} (G : SimpleGraph (Fin n))
    (j : ℕ) (M : ℕ → ℕ) (C : ℕ → ℕ → ℕ) (σ : Env) : Prop :=
  ∀ (i : ℕ) (hi : i < (tablesAt q_top cap mb φ j).length), ∃ Tb : ℕ → ℕ,
    σ.arrs (tabName j i) = arrOf n Tb ∧ (∀ v < n, Tb v ≤ 1) ∧
    ∀ v : Fin n, (Tb (v : ℕ) ≠ 0 ↔
      Sat (masked G M) (colRead n C (sigL cap mb j)) (fun _ => v)
        (tablesAt q_top cap mb φ j)[i])

/-- **The table arrays of every depth, at the carrier's length.** A
depth's tables are *written* by the level of that depth and by nothing
else, so no postcondition below produces this clause and no
precondition below can do without it: an out-of-range store has no
derivation in IMP+. It is depth-independent because a level runs the
level below it, which stores into *its* tables while the enclosing turn
is still holding this clause. -/
def TablesSized (q_top cap mb : ℕ) (φ : Lax3.FirstOrder.FO 0) (n : ℕ) (σ : Env) : Prop :=
  ∀ j : ℕ, Sized ((List.range (tablesAt q_top cap mb φ j).length).map
    fun i => (tabName j i, n)) σ

/-- One table array of one depth, out of the clause. -/
theorem TablesSized.get {q_top cap mb n : ℕ} {φ : Lax3.FirstOrder.FO 0} {σ : Env}
    (h : TablesSized q_top cap mb φ n σ) (j : ℕ) {i : ℕ}
    (hi : i < (tablesAt q_top cap mb φ j).length) :
    ∃ g : ℕ → ℕ, σ.arrs (tabName j i) = arrOf n g :=
  h j _ (List.mem_map.2 ⟨i, List.mem_range.2 hi, rfl⟩)

/-- **The clause survives any run**, since a run cannot change the
length of an array. -/
theorem TablesSized.run {B q_top cap mb n : ℕ} {φ : Lax3.FirstOrder.FO 0} {c : Com}
    {σ σ' : Env} {K : ℕ} (h : TablesSized q_top cap mb φ n σ) (hr : Run B c σ σ' K) :
    TablesSized q_top cap mb φ n σ' := fun j => (h j).run hr

/-- The block structure, the two masks and the memory of a depth, as
the machine holds them. Everything a level reads and nothing it writes,
together with the two clauses no statement about *sets* carries: that
the arrays the passes below address are there at the lengths they
address them at, and that the two masks hold words. -/
def LevelPre (B n : ℕ) (cap mb : ℕ) (ns : ℕ) (O T : ℕ → ℕ) (j : ℕ) (M Gm : ℕ → ℕ)
    (C : ℕ → ℕ → ℕ) (σ : Env) : Prop :=
  σ.vars "n" = n ∧ σ.arrs "off" = arrOf (n + 1) O ∧ σ.arrs "tgt" = arrOf ns T ∧
    σ.arrs (alvName j) = arrOf n M ∧ σ.arrs (gamName j) = arrOf n Gm ∧
    (∀ c < sigL cap mb j, σ.arrs (colName j c) = arrOf n (C c)) ∧
    (∀ z < n, M z < B) ∧ (∀ z < n, Gm z < B) ∧ LevelMem B n σ

/-- What a level leaves: its tables, and everything it was handed,
untouched. The second half is what makes the levels compose — a level
above reads its own masks and colours after the level below has run. -/
def LevelPost (B q_top cap mb : ℕ) (φ : Lax3.FirstOrder.FO 0) {n : ℕ}
    (G : SimpleGraph (Fin n)) (ns : ℕ) (O T : ℕ → ℕ) (j : ℕ) (M Gm : ℕ → ℕ)
    (C : ℕ → ℕ → ℕ) (_σ σ' : Env) : Prop :=
  LevelPre B n cap mb ns O T j M Gm C σ' ∧ TablesSized q_top cap mb φ n σ' ∧
    TableInv q_top cap mb φ G j M C σ'

/-! ### The obligations

Each is a `Prop` stated over the program text and the input surface a
caller has, so each is a self-contained obligation and not a hole in a
statement. Each docstring splits it into its sub-walks, in the manner of
`Lax3Proofs.RamElim.Implements`, and names what discharges each of them.
The two engines enter as availabilities — `Lax3Proofs.RamElim.Implements`
and `Lax3Proofs.RamAugment.Implements` with the call's own data
quantified away — exactly as `Lax3Proofs.RamAugment.ElimAvail` does, so
that discharging those two discharges every sub-call of the driver
without moving a signature here. -/

section Obligations

variable (B : ℕ) {n : ℕ}

/-! Every phase of the driver is a program of the *bounded* semantics,
in which an expression above the word size has no value at all and a
command reading one has no derivation. So every obligation carries a
value bound, and one bound serves them all: the widest address any pass
of a level forms is the cluster arena's `n * n`, the block structure's
`ns`, and the search's `2 * cap`. `WordBound` is their sum, and the
four readings below are how the sub-programs' own bounds come off it. -/

/-- **The value bound of a level**: every address any pass of a level
forms is a word. -/
def WordBound (n ns cap : ℕ) : Prop := n * n + ns + 2 * cap + 2 < B

variable {B}

theorem le_mul_self (n : ℕ) : n ≤ n * n := by
  rcases Nat.eq_zero_or_pos n with rfl | hn
  · omega
  · exact Nat.le_mul_of_pos_left n hn

theorem WordBound.one_lt {n ns cap : ℕ} (h : WordBound B n ns cap) : 1 < B := by
  rw [WordBound] at h; omega

theorem WordBound.n_lt {n ns cap : ℕ} (h : WordBound B n ns cap) : n < B := by
  rw [WordBound] at h
  have := le_mul_self n
  omega

theorem WordBound.succ_lt {n ns cap : ℕ} (h : WordBound B n ns cap) : n + 1 < B := by
  rw [WordBound] at h
  have := le_mul_self n
  omega

theorem WordBound.ns_lt {n ns cap : ℕ} (h : WordBound B n ns cap) : ns < B := by
  rw [WordBound] at h; omega

/-- The bound `RamCover.Implements` asks for, at the radius the driver
calls the cover at. -/
theorem WordBound.cover {n ns cap : ℕ} (h : WordBound B n ns cap) :
    n * n + ns + 2 * cap + 2 < B := h

variable (B)

/-- The elimination engine, available at every arena and slot count the
driver calls it at. -/
def ElimAvail (n : ℕ) : Prop :=
  ∀ (F : SimpleGraph (Fin n)) (ns : ℕ) (M O T : ℕ → ℕ), RamElim.Implements B n ns F M O T

/-- The augmentation round, available at every orientation the driver
calls it at. -/
def AugAvail (n : ℕ) : Prop :=
  ∀ (d nf W m : ℕ) (D : Augmentation.Orientation n) (DO DT : ℕ → ℕ),
    RamAugment.Implements B n d nf W m D DO DT

/-- The cover pass, available at every arena and ordering the driver
calls it at. -/
def CoverAvail (cap ns : ℕ) (G : SimpleGraph (Fin n)) (O T : ℕ → ℕ) : Prop :=
  ∀ (A₀ ord : ℕ → ℕ) (π : Equiv.Perm (Fin n)),
    RamCover.Implements B n ns G A₀ O T ord π cap

/-- **The memory the ordering pass addresses**, on top of the level's
own: the scratch arrays of `Lax3Proofs.RamElim.ElimPre` and of
`Lax3Proofs.RamAugment.AugPre`, at the width the driver allocates them
at, with the accumulators, the elimination flags, the bucket heads and
the four stamps zeroed — which is what a machine's fresh memory already
says. -/
def OrderMem (n ns W : ℕ) (σ : Env) : Prop :=
  Sized [("doff", n + 1), ("dtg", W), ("ooff", n + 1), ("otg", W), ("ofl", n),
      ("gof", n + 1), ("gtg", ns), ("ffl", n), ("deg", n), ("rnk", n), ("idg", n),
      ("bh", n + 1), ("bv", n + W + 1), ("bn", n + W + 1), ("ioff", n + 1), ("ifl", n),
      ("itg", W), ("noff", n + 1), ("nfl", n), ("ntg", W), ("elm", n),
      ("stf", n), ("sta", n), ("std", n), ("ste", n)] σ ∧
    (∀ v ∈ σ.arrs "elm", v = 0) ∧ (∀ v ∈ σ.arrs "bh", v = 0) ∧
    (∀ v ∈ σ.arrs "ooff", v = 0) ∧ (∀ v ∈ σ.arrs "noff", v = 0) ∧
    (∀ v ∈ σ.arrs "stf", v = 0) ∧ (∀ v ∈ σ.arrs "sta", v = 0) ∧
    (∀ v ∈ σ.arrs "std", v = 0) ∧ (∀ v ∈ σ.arrs "ste", v = 0)

/-- **The decode.** That `decodeCom` reads the tape encoding into the
block structure and opens the root arena with everything alive.

It splits into three walks.

* The two counts and the two read loops are `Lax11Proofs.CC`'s reading
  phase verbatim: one `Spec.read` apiece and two applications of
  `Spec.forRangeZero` whose body is a read and a store, with the length
  of the input word as the value bound.
* `RamBfs.csrGraph_of_encodesGraph` turns what the loops left into
  `RamBfs.CsrGraph G (2 * edgeCount x) O T`, which is the block
  structure every pass below reads. Nothing else is asked of the
  encoding.
* The two fills are `Fill.loop_spec` with the constant one, and
  `RamElim.masked_of_all_alive` is why the arena they open is `G`
  itself.

Two clauses are not about the encoding. `DecodeMem` is the four arrays
the phase writes, at the lengths it writes them at: an out-of-range
store is *stuck* in IMP+ rather than defaulted, and the phase's first
act is a store into `off`, so without it the obligation is refuted by
the state whose arrays are all empty. The value bounds are the same
rule at the expressions: at `B = 0` nothing evaluates. -/
def DecodeImplements (x : List ℕ) (G : SimpleGraph (Fin n)) (ns : ℕ)
    (O T : ℕ → ℕ) (K : ℕ) : Prop :=
  (∀ v ∈ x, v < B) → n + 1 < B → ns < B →
    Spec B (fun σ => DecodeMem n ns σ ∧ σ.inp = x ∧ σ.out = []) decodeCom
      (fun _ σ' => σ'.out = [] ∧ CsrGraph G ns O T ∧
        σ'.vars "n" = n ∧ σ'.arrs "off" = arrOf (n + 1) O ∧ σ'.arrs "tgt" = arrOf ns T ∧
        (∃ M, σ'.arrs (alvName 0) = arrOf n M ∧ ∀ v < n, M v = 1) ∧
        (∃ Gm, σ'.arrs (gamName 0) = arrOf n Gm ∧ ∀ v < n, Gm v = 1)) K

/-- **The ordering pass.** That `orderCom R W j` leaves in `ord` the
order array of an ordering of the depth's arena along which the cover
has the degree `Lax3Proofs.CoverDegree.exists_cover_degree` bounds.

It splits along its five phases.

* The first `RamElim.elimCom` enters through `RamElim.elim_spec`, whose
  `Implements` is `ElimAvail`'s; its postcondition `RamElim.ElimPost`
  hands back an orientation of the arena with its in-lists, which is the
  chain's round zero.
* The `R` rounds enter through `RamAugment.augment_spec`, whose
  `Implements` is `AugAvail`'s and whose `ElimAvail` is this one's; the
  chain they build is collected by `RamAugment.isAugChain_succ` and
  `RamAugment.greedyFratRound_succ`, and the in-degree budget the width
  `W` is cut to is `CoverDegree.joint_le`'s closed form.
* `augRelinkCom` is the composition surface of `RamAugment`: two copies
  and seven fills, all `Fill.loop_spec`.
* `symCom` is the counting sort that materializes the last round's graph
  undirected, so that the final elimination reads a `RamElim.CsrSimple`.
* The final `RamElim.elimCom` gives the ranking, and `ordCom` inverts it;
  `RamCover.ordersBy_rankPerm` is the one line that turns the rank array
  and its inverse into `RamCover.OrdersBy`.

The postcondition says only that the array orders *some* permutation,
and that is deliberate: nothing in the driver's **correctness** depends
on which ordering the cover is taken along, since
`RamCover.cover_spec` produces a neighborhood cover from any
`RamCover.OrdersBy`. What the ordering is for is the **degree** of that
cover, hence the driver's cost, which
`Lax3Proofs.CoverDegree.exists_cover_degree` bounds from the chain this
pass builds. That bound therefore belongs to the cost `K` and to the
wave that computes it, not here.

**The one memory clause not folded in.** `OrderMem` below is what the
two engines address and the level's own state does not — the twenty-odd
scratch arrays of `Lax3Proofs.RamAugment.AugPre` and of
`Lax3Proofs.RamElim.ElimPre`, with the accumulators, the flags and the
stamps zeroed — and it is *not* a conjunct of this obligation, because
it cannot be one until two things change together.

* Its lengths are cut to the augmentation width `W`, so carrying it
  across a level means carrying `W` in `LevelPre`, and hence in every
  obligation and every phase `Prop` below. That is a signature change
  and not a repair.
* `orderCom` does not restore the zeroing: the final `RamElim.elimCom`
  leaves `elm` and `bh` used, and there is no re-zeroing tail after it.
  So `OrderMem` at the exit is *false* of the program as written, and a
  level cannot hand it to the level below. A re-zeroing tail — nine
  `fillCom`s, the shape `augRelinkCom` already has — is the program
  repair that comes with the signature change.

`Lax3Proofs.RamElim.ElimPre`'s pinning of `tgt`, `itg`, `bv` and `bn`
to *exactly* the slot count of the call is the third half of the same
knot: the fraternity graph's slot count is data-dependent, so a caller
that allocates once, at `W`, cannot satisfy it. Relaxing that pinning
to "at least the slot count" is what makes `OrderMem` statable at `W`
at all. -/
def OrderImplements (n R W cap mb ns j : ℕ) (O T : ℕ → ℕ)
    (M Gm : ℕ → ℕ) (C : ℕ → ℕ → ℕ) (K : ℕ) : Prop :=
  WordBound B n ns cap → n + W + 1 < B →
  ElimAvail B n → AugAvail B n →
    Spec B (fun σ => LevelPre B n cap mb ns O T j M Gm C σ)
      (orderCom R W j)
      (fun σ σ' => LevelPre B n cap mb ns O T j M Gm C σ' ∧
        σ'.out = σ.out ∧
        ∃ (π : Equiv.Perm (Fin n)) (ord : ℕ → ℕ),
          σ'.arrs "ord" = arrOf n ord ∧ RamCover.OrdersBy n π ord) K

/-- **The cover pass at a level.** That the copy of the depth's mask
followed by `RamCover.coverCom cap` leaves the clusters and the
assignment of an `cap`-neighborhood cover of the depth's arena.

Two walks and no mathematics: the copy is `Fill.loop_spec`, and the pass
itself is `RamCover.cover_spec` at the ordering the previous obligation
produced, whose own `Implements` is `CoverAvail`'s. The copy is what
makes the destructiveness of the pass harmless — it kills the centres in
`alv`, which is the *copy* of `alvName j`. -/
def CoverImplements (cap mb ns j : ℕ) (G : SimpleGraph (Fin n)) (O T : ℕ → ℕ)
    (M Gm : ℕ → ℕ) (C : ℕ → ℕ → ℕ) (π : Equiv.Perm (Fin n)) (ord : ℕ → ℕ) (K : ℕ) : Prop :=
  WordBound B n ns cap →
  CoverAvail B cap ns G O T → RamCover.OrdersBy n π ord →
    Spec B (fun σ => LevelPre B n cap mb ns O T j M Gm C σ ∧ σ.arrs "ord" = arrOf n ord)
      (.seq (copyCom (alvName j) "alv") (RamCover.coverCom cap))
      (fun σ σ' => LevelPre B n cap mb ns O T j M Gm C σ' ∧ σ'.out = σ.out ∧
        σ'.arrs "ord" = arrOf n ord ∧ RamCover.CoverPost G M π ord cap σ σ') K

/-! ### The readback of one cluster

There is no `ReadbackImplements` here, and the `Prop` that used to
stand in this place was not provable. It handed the atoms' valuation as
a function of the *entering* state, so a local atom — whose truth
varies from vertex to vertex, since `atomExpr` reads the depth-`(j+1)`
table at the vertex the counter stands on — was evaluated at whatever
the scalar `z` happened to hold before the loop started, and the stated
`Prop` could not express what the loop leaves.
`Lax3Proofs.RamDriverCluster.ReadbackStep` is that obligation with the
valuation indexed by the vertex, which is the shape
`sat_iff_eval_step` produces and the shape
`Lax3Proofs.RamDriverBase.readbackStep` discharges; the cluster step
consumes it there and not here. -/

/-- **One cluster.** That the turn of the loop over the centres writes
the depth-`(j+1)` state, runs the nested driver, decides the scatter
atoms and reads back — leaving the tables of the cluster's own vertices
correct.

It splits along the turn's six passes.

* `descendCom` is nine flat passes and one chain of expansions. Its
  content is the two mask equations: the work arena of the next depth is
  `stepArenaP` at the cluster and the batch, and the game arena is
  `SplitterWinOracle.nextArenaO` at the ball and the same batch. The
  expansion chain that builds the ball is `expandCom` iterated `2·cap`
  times, whose own content is one step of `WithinDist`.
* `batchCom` is `SplitterWinOracle.genSetO` written out: the connector,
  then one call of `RamBfsPaths.bfsPathCom` per earlier round in *that*
  round's game mask. `RamBfsPaths.bfsPath_spec` is the call, and the
  oracle it instantiates is the recipe in that file's final section.
* `enumBatch` is the padding, and `exists_pad_enum` — proved above — is
  what its result is worth.
* `colourCom` is `Evaluator.isoColoring`'s three slot equations, each an
  expansion chain: `oldCom` for `slotOld`, `pdCom` for `slotPd`, `puCom`
  for `slotPu`.
* The nested driver enters as the hypothesis `inner`, exactly as
  `RamElim.Implements` enters `RamAugment.Implements`.
* The scatter atoms enter through `RamScatter.scatter_spec`, one call per
  atom, at the depth-`(j+1)` table row of the atom's own formula, and the
  readback through `Lax3Proofs.RamDriverCluster.ReadbackStep`. -/
def ClusterStepImplements (q_top cap mb ns j : ℕ) (φ : Lax3.FirstOrder.FO 0)
    (G : SimpleGraph (Fin n)) (O T : ℕ → ℕ) (M Gm : ℕ → ℕ) (C : ℕ → ℕ → ℕ)
    (π : Equiv.Perm (Fin n)) (ord : ℕ → ℕ) (inner : Com) (Kin K : ℕ) : Prop :=
  WordBound B n ns cap →
  (∀ (M' Gm' : ℕ → ℕ) (C' : ℕ → ℕ → ℕ),
      Spec B (fun σ => LevelPre B n cap mb ns O T (j + 1) M' Gm' C' σ ∧
          TablesSized q_top cap mb φ n σ) inner
        (fun σ σ' => LevelPost B q_top cap mb φ G ns O T (j + 1) M' Gm' C' σ σ' ∧
          σ'.out = σ.out) Kin) →
    Spec B (fun σ => LevelPre B n cap mb ns O T j M Gm C σ ∧
        TablesSized q_top cap mb φ n σ ∧ σ.arrs "ord" = arrOf n ord ∧
        σ.vars "c" < n ∧ RamCover.CoverPost G M π ord cap σ σ)
      (clusterCom q_top cap mb φ j inner)
      (fun σ σ' => LevelPre B n cap mb ns O T j M Gm C σ' ∧
        TablesSized q_top cap mb φ n σ' ∧ σ'.out = σ.out ∧
        σ'.vars "c" = σ.vars "c" ∧
        ∀ (i : ℕ) (hi : i < (tablesAt q_top cap mb φ j).length), ∃ Tb : ℕ → ℕ,
          σ'.arrs (tabName j i) = arrOf n Tb ∧
          ∀ v : Fin n, ∀ asg : ℕ → ℕ, σ'.arrs "asg" = arrOf n asg → asg (v : ℕ) = σ.vars "c" →
            Tb (v : ℕ) ≤ 1 ∧
            (Tb (v : ℕ) ≠ 0 ↔
              Sat (masked G M) (colRead n C (sigL cap mb j)) (fun _ => v)
                (tablesAt q_top cap mb φ j)[i])) K

/-- **The base case.** That `baseCom` leaves, at every vertex, the truth
value of every formula of the bottom table on the edgeless arena.

It splits into two walks.

* `reprCom` is a nested scan whose content is
  `BotEval.exists_offRepr`'s conclusion: every vertex has a same-row
  companion among the recorded ones. `BotEval.rowOf_eq_iff` is the
  translation between the row equality the scan tests — a product of
  `eqBitExpr`s over the depth's colour arrays — and the pointwise
  colour agreement the transfer lemmas ask for, and
  `BotEval.ncard_le_of_injOn_rowOf` is why the record stays below
  `2 ^ (sigL cap mb ℓ)`.
* `botCom` is an induction on the formula. The five atoms are
  `BotEval.sat_adj_bot`, `sat_eq_bot`, `sat_color_bot`, `sat_distLe_bot`
  and `sat_distColorLt_bot`; the local quantifier is `sat_exL_bot`, its
  guard set loaded as a straight line of stores; the unrestricted one is
  `BotEval.sat_exU_bot_of_repr`, weakened by `sat_exU_bot_of_repr_all`
  below so that the loop need not test whether a representative lies off
  the environment. The fresh-name discipline — one character per level of
  the formula — is what makes the frame conditions of the nested walks
  decidable.

The hypothesis is that the arena is edgeless, which
`eq_bot_of_playOk_full` supplies at depth `ℓ`.

Two clauses beyond the level's own state. `TablesSized` is the depth's
table arrays at the carrier's length, which nothing below produces and
without which the walk's stores have no derivation; `rep` at
`2 ^ sigL cap mb ℓ` is the representative system `reprCom` builds, and
the environment slots are the base evaluator's own — one per free
variable of the deepest formula, which `envDepth` bounds. -/
def BaseImplements (q_top cap mb ns ℓ : ℕ) (φ : Lax3.FirstOrder.FO 0)
    (G : SimpleGraph (Fin n)) (O T : ℕ → ℕ) (M Gm : ℕ → ℕ) (C : ℕ → ℕ → ℕ) (K : ℕ) : Prop :=
  WordBound B n ns cap → 2 ^ sigL cap mb ℓ < B → masked G M = ⊥ →
    Spec B (fun σ => LevelPre B n cap mb ns O T ℓ M Gm C σ ∧
        TablesSized q_top cap mb φ n σ ∧ Sized [("rep", 2 ^ sigL cap mb ℓ)] σ)
      (baseCom q_top cap mb ℓ φ)
      (fun σ σ' => LevelPost B q_top cap mb φ G ns O T ℓ M Gm C σ σ' ∧ σ'.out = σ.out) K

open Classical in
/-- **The sentence readback.** That `sentenceCom` writes the one bit the
whole program produces.

Two walks. The scatter atoms enter through `RamScatter.scatter_spec`,
one call per atom of the top sentence's combination, at the depth-zero
table row of the atom's own formula — which `TableInv` at depth zero says
is the set the atom speaks about. The write is `Spec.write` at `bcExpr`
of the combination, whose local atoms are the *constants*
`Evaluator.localSentenceEval` decides at construction time. What the bit
means is `sat_iff_eval_sentence`, proved above. -/
def SentenceImplements (q_top cap mb ns : ℕ) (φ : Lax3.FirstOrder.FO 0)
    (G : SimpleGraph (Fin n)) (O T : ℕ → ℕ) (M Gm : ℕ → ℕ) (C : ℕ → ℕ → ℕ) (K : ℕ) : Prop :=
  WordBound B n ns cap → (∀ v < n, M v ≠ 0) →
    Spec B (fun σ => LevelPre B n cap mb ns O T 0 M Gm C σ ∧
        TableInv q_top cap mb φ G 0 M C σ ∧ σ.out = [])
      (sentenceCom q_top cap mb φ)
      (fun _ σ' => ∃ h : ∃ q' : ℕ, q' ≤ q_top ∧
          DRank 0 q' (Reduction.toDistFO (L := sigL cap mb 0) φ),
        σ'.out = [if (bcOf₀ q_top (Reduction.toDistFO (L := sigL cap mb 0) φ) h).eval
            (Sum.elim Evaluator.localSentenceEval
              (fun σs : ScatterSentence (sigL cap mb 0) =>
                σs.t ≤ (greedySet (masked G M) σs.r
                  {a | Sat (masked G M) (colRead n C (sigL cap mb 0))
                    (fun _ => a) σs.β}).ncard))
          then 1 else 0]) K

/-- **One level.** That `driverAt … j` establishes the table invariant of
its depth.

This is the composition, and it carries its six sub-walks as hypotheses
of its own, so that discharging each of them discharges this one's
corresponding phase without moving any signature here. It splits in two
along the fuel.

* At `j = ℓ` it is `BaseImplements`, and the hypothesis that hypothesis
  wants — that the arena is edgeless — is `eq_bot_of_playOk_full` at the
  game invariant the levels above maintained.
* Below `ℓ` it is `OrderImplements`, `CoverImplements`, and
  `Spec.forRangeZero` over the centres with `ClusterStepImplements` as
  its body, the nested driver entering that body as its own hypothesis.
  What the loop leaves is the table invariant of the depth: the turns
  partition the carrier, since `RamCover.CoverOut.asg_lt` assigns every
  vertex to exactly one centre, and each turn is correct on its own
  vertices by `sat_iff_eval_step` at the cluster it processed and the
  batch its searches produced. -/
def LevelImplements (q_top cap mb R ℓ W ns j : ℕ) (φ : Lax3.FirstOrder.FO 0)
    (G : SimpleGraph (Fin n)) (O T : ℕ → ℕ) (M Gm : ℕ → ℕ) (C : ℕ → ℕ → ℕ) (K : ℕ) : Prop :=
  Spec B (fun σ => LevelPre B n cap mb ns O T j M Gm C σ ∧ TablesSized q_top cap mb φ n σ)
    (driverAt q_top cap mb R ℓ W φ j)
    (fun σ σ' => LevelPost B q_top cap mb φ G ns O T j M Gm C σ σ' ∧ σ'.out = σ.out) K

end Obligations

/-! ### The base case's witness search, weakened

`BotEval.sat_exU_bot_of_repr` tests whether a representative lies off the
environment's range, which a machine loop would have to check by
comparing against every entry. It does not have to: a representative
that *is* an entry contributes a disjunct the environment's own half
already contributes, so dropping the test changes nothing. This is the
form the generated loop of `botCom` is proved against. -/

/-- **The witness search, without the off-tuple test.** -/
theorem sat_exU_bot_of_repr_all {L k : ℕ} {col : Coloring n L} {m : Fin k → Fin n}
    (ψ : DistFO L (k + 1)) (Wr : Set (Fin n))
    (hW : ∀ v ∉ Set.range m, ∃ w ∈ Wr, w ∉ Set.range m ∧ ∀ c : Fin L, v ∈ col c ↔ w ∈ col c) :
    Sat (⊥ : SimpleGraph (Fin n)) col m (.exU ψ) ↔
      (∃ i, Sat (⊥ : SimpleGraph (Fin n)) col (Fin.snoc m (m i)) ψ) ∨
        ∃ w ∈ Wr, Sat (⊥ : SimpleGraph (Fin n)) col (Fin.snoc m w) ψ := by
  constructor
  · intro h
    rcases (BotEval.sat_exU_bot_of_repr ψ Wr hW).mp h with h' | ⟨w, hwW, -, hw⟩
    · exact Or.inl h'
    · exact Or.inr ⟨w, hwW, hw⟩
  · rintro (⟨i, hi⟩ | ⟨w, -, hw⟩)
    · exact (sat_exU ψ).mpr ⟨m i, hi⟩
    · exact (sat_exU ψ).mpr ⟨w, hw⟩

/-! ### The theorem

The three phases of the root, composed. The decode opens the arena, the
driver at depth zero establishes the table invariant there, and the
sentence readback turns that invariant into the one bit — by
`sat_iff_eval_sentence`, which is the only mathematics in this proof.

The cost is a parameter: what the driver costs is a separate wave's
business, and the composition adds the three phases' own. -/

section Main

variable {n ns : ℕ} {B q_top cap mb R ℓ W Kd Kl Ks : ℕ} {G : SimpleGraph (Fin n)}
  {O T : ℕ → ℕ} {x : List ℕ} {φ : Lax3.FirstOrder.FO 0}

open Classical in
/-- **The driver decides the sentence.** Handed the tape encoding of a
graph, `driverRoot` writes `[1]` if the sentence holds in it and `[0]` if
it does not.

Everything about the machine is a hypothesis: the decode, the level at
depth zero, and the sentence readback, each a `Prop` about the program
text stated above. What the theorem contributes is the *meaning* of the
bit the last of them writes — that the boolean combination of the top
sentence, evaluated over the constants its local atoms are and the greedy
scatter values its scatter atoms are, is the sentence's truth value.
That is `sat_iff_eval_sentence`, and it is the only step of this proof
that is not composition. -/
theorem driver_correct (hrank : Lax3.FirstOrder.rank φ ≤ q_top)
    (hB : WordBound B n ns cap) (hxB : ∀ v ∈ x, v < B)
    (hdec : DecodeImplements B x G ns O T Kd)
    (hlev : ∀ (M Gm : ℕ → ℕ) (C : ℕ → ℕ → ℕ), (∀ v < n, M v ≠ 0) →
      LevelImplements B q_top cap mb R ℓ W ns 0 φ G O T M Gm C Kl)
    (hsent : ∀ (M Gm : ℕ → ℕ) (C : ℕ → ℕ → ℕ),
      SentenceImplements B q_top cap mb ns φ G O T M Gm C Ks) :
    Spec B (fun σ => DecodeMem n ns σ ∧ LevelMem B n σ ∧ TablesSized q_top cap mb φ n σ ∧
        σ.inp = x ∧ σ.out = [])
      (driverRoot q_top cap mb R ℓ W φ)
      (fun _ σ' => σ'.out = [if Lax3.FirstOrder.Sat G Fin.elim0 φ then 1 else 0])
      (Kd + (Kl + Ks)) := by
  classical
  refine Spec.of_exists fun σ hσ => ?_
  obtain ⟨hdm, hmem, htsz, hinp, hout⟩ := hσ
  -- the decode
  obtain ⟨σ₁, hrun₁, hout₁, hcsr, hn₁, hoff₁, htgt₁, ⟨M, hM₁, hMone⟩, ⟨Gm, hGm₁, hGmone⟩⟩ :=
    (hdec hxB hB.succ_lt hB.ns_lt).run ⟨hdm, hinp, hout⟩
  -- the memory the decode was handed is the memory the level is handed
  have hmem₁ : LevelMem B n σ₁ := levelMem_run hrun₁ hmem
  have htsz₁ : TablesSized q_top cap mb φ n σ₁ := htsz.run hrun₁
  -- the masks the root opens are the constant one, hence words and nowhere zero
  have hMpos : ∀ v < n, M v ≠ 0 := fun v hv => by rw [hMone v hv]; omega
  have hMB : ∀ z < n, M z < B := fun z hz => by rw [hMone z hz]; exact hB.one_lt
  have hGmB : ∀ z < n, Gm z < B := fun z hz => by rw [hGmone z hz]; exact hB.one_lt
  -- the level, at the colouring the root has: the empty palette
  have hcolempty : ∀ c < sigL cap mb 0, σ₁.arrs (colName 0 c) = arrOf n (fun _ => 0) := by
    intro c hc
    exact absurd hc (by rw [sigL_zero]; omega)
  obtain ⟨σ₂, hrun₂, ⟨hpre₂, -, htab₂⟩, hout₂⟩ :=
    (hlev M Gm (fun _ _ => 0) hMpos).run
      (σ := σ₁) ⟨⟨hn₁, hoff₁, htgt₁, hM₁, hGm₁, hcolempty, hMB, hGmB, hmem₁⟩, htsz₁⟩
  -- the sentence readback
  obtain ⟨σ₃, hrun₃, hcond, hout₃⟩ :=
    (hsent M Gm (fun _ _ => 0) hB hMpos).run (σ := σ₂) ⟨hpre₂, htab₂, by rw [hout₂, hout₁]⟩
  refine ⟨σ₃, _, (hrun₁.seq (hrun₂.seq hrun₃)).mono le_rfl, le_rfl, ?_⟩
  -- and the one thing that is not composition
  rw [hout₃]
  congr 1
  refine if_congr ?_ rfl rfl
  have hMG : masked G M = G := RamElim.masked_of_all_alive G hMpos
  have hglue := sat_iff_eval_sentence (mb := mb) (cap := cap) hrank (masked G M)
    (colRead n (fun _ _ => 0) (sigL cap mb 0)) hcond
  exact hglue.symm.trans (by rw [hMG])

end Main

end Lax3Proofs.RamDriver


