name = "Lax4Proofs"
defaultTargets = ["Lax4Proofs"]

[leanOptions]
autoImplicit = true

[[require]]
name = "Lax4"
path = "../concepts"

[[lean_lib]]
name = "Lax4Proofs"

# twin-width tower: transparent definitions of submission Lax3
[[require]]
name = "Lax3"
git = "/home/jan/git/lax-submissions-origin.git"
rev = "92ab044198069b03cd9d0729898e8ca055445699"
subDir = "twin-width-treewidth-exponential-reviewable/concepts"
