name = "Lax2Proofs"
defaultTargets = ["Lax2Proofs"]

[leanOptions]
autoImplicit = true

[[require]]
name = "Lax2"
path = "../concepts"

[[lean_lib]]
name = "Lax2Proofs"

# twin-width tower: transparent definitions of submission Lax1
[[require]]
name = "Lax1"
git = "/home/jan/git/lax-submissions-origin.git"
rev = "72bc4ac2e7099c4db613d48fb48a7c4380e2f7d7"
subDir = "twin-width-treewidth-exponential/concepts"
