import Lax15Proofs.Config
import Lax15Proofs.Config3
import Lax15Proofs.Loop
import Lax15Proofs.Loop3
import Lax15Proofs.Main
import Lax15Proofs.Main3
import Lax15Proofs.MainFpt
import Lax15Proofs.Phases
import Lax15Proofs.Phases3
import Lax15Proofs.Program
import Lax15Proofs.Program3
import Lax15Proofs.Residual
import Lax15Proofs.Solver
import Lax15Proofs.Sweep3
import Lax15Proofs.Repeats
