import Lax3Proofs.WalkDistance
import Lax3Proofs.Horizon
import Lax3Proofs.Clusters
import Lax3Proofs.ScatterCore
import Lax3Proofs.SemLocal
import Lax3Proofs.SyntaxLemmas
import Lax3Proofs.Separation
import Lax3Proofs.FarQuant
import Lax3Proofs.BCAlgebra
import Lax3Proofs.ScatterFml
